(()=>{'use strict';
const S=window.RitmiStorage, root=document.body;
const pad=n=>String(n).padStart(2,'0');
const iso=d=>{const x=new Date(d);return `${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`};
const today=iso(new Date());
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty=s=>new Date(`${s}T12:00:00`).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});
const monthName=d=>d.toLocaleDateString(undefined,{month:'long',year:'numeric'});
let D,route='today',selected=today,monthCursor=new Date(`${today}T12:00:00`),overlay=null;
const fields={bleeding:['none','spotting','light','medium','heavy'],pain:['none','mild','moderate','strong'],mood:['low','okay','good','high'],energy:['low','medium','high'],sleep:['poor','okay','good']};
const symptomList=['cramps','headache','bloating','breast tenderness','nausea','back pain','fatigue','acne','constipation','diarrhea','dizziness','cravings','insomnia'];
const knowledge=[
 ['Cycle basics','The menstrual cycle is a pattern, not a promise. Learn the phases and why length can vary.'],
 ['Periods & bleeding','Understand period days, spotting and why your own history is more useful than a generic “normal”.'],
 ['Symptoms','A plain-language index for common symptoms. Tracking is observation, not diagnosis.'],
 ['Body literacy','Useful terms, observations and questions for understanding patterns over time.'],
 ['Privacy by design','What local storage means, what an export contains, and how to keep your backup yours.']
];
function periods(){return [...(D.periods||[])].map(x=>String(x.date||x)).filter(Boolean).sort()}
function periodSet(){return new Set(periods())}
function cycles(){const p=periods(), lengths=[];for(let i=1;i<p.length;i++)lengths.push(Math.round((new Date(p[i])-new Date(p[i-1]))/86400000));return {p,lengths,avg:lengths.length?Math.round(lengths.reduce((a,b)=>a+b,0)/lengths.length):null}}
function lastPeriod(){return periods().at(-1)||null}
function addDays(s,n){const d=new Date(`${s}T12:00:00`);d.setDate(d.getDate()+Number(n));return iso(d)}
function cycleDay(){const p=lastPeriod();return p?Math.max(1,Math.floor((new Date(today)-new Date(p))/86400000)+1):null}
function logged(k){return !!((D.logs?.[k]&&Object.keys(D.logs[k]).length)||D.notes?.[k])}
async function save(){await S.save(D);D=await S.snapshot()}
function shell(){root.innerHTML=`<div id="ritmi-app"><header class="r-header"><button class="r-word" onclick="Ritmi.go('today')">ritmi</button><div class="r-headtools"><button class="r-datejump" onclick="Ritmi.jumpToday()">${new Date(`${selected}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</button><button class="r-menu" onclick="Ritmi.menu()" aria-label="Open navigation"><span></span><span></span></button></div></header><main id="r-main"></main><div id="r-layer"></div></div>`;render()}
function render(){const m=document.querySelector('#r-main');if(!m)return;({today:todayView,track:trackView,calendar:calendarView,knowledge:knowledgeView,more:moreView,insights:insightsView}[route]||todayView)(m)}
function label(s){return `<div class="r-eyebrow">${s}</div>`}
function todayView(m){const day=cycleDay(),p=lastPeriod(),st=cycles(),next=p?addDays(p,D.settings?.cycleLength||28):null;const l=D.logs?.[today]||{};m.innerHTML=`<section class="r-page r-home">${label('Today')}<h1>${day?`Day ${day}`:'Begin with yourself.'}</h1><p class="r-sub">${day?'A quiet picture of where you are right now.':'Ritmi works from the days you choose to record. Nothing is required.'}</p><div class="r-cycle-visual"><div class="r-halo"></div><div class="r-cycle-core"><strong>${day||'—'}</strong><span>${day?'cycle day':'not started'}</span></div><div class="r-cycle-caption">${next?`Expected around ${new Date(`${next}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'})}`:'Record a period to begin your history'}</div></div><div class="r-quick"><button onclick="Ritmi.openTrack()"><i>＋</i><span>Record today</span></button><button onclick="Ritmi.markPeriod()"><i>${periodSet().has(today)?'✓':'○'}</i><span>${periodSet().has(today)?'Period recorded':'Mark period'}</span></button><button onclick="Ritmi.go('calendar')"><i>◌</i><span>Open calendar</span></button></div><div class="r-section"><div class="r-sectiontitle">Today, if you want</div><div class="r-todayline"><span>Bleeding</span><b>${l.bleeding||'—'}</b></div><div class="r-todayline"><span>Mood</span><b>${l.mood||'—'}</b></div><div class="r-todayline"><span>Symptoms</span><b>${l.symptoms?.length?l.symptoms.length+' recorded':'—'}</b></div></div><div class="r-section r-story"><span class="r-smalllabel">Your rhythm</span><p>${st.avg?`Your recorded cycles average ${st.avg} days. Ritmi keeps this as an observation, not a prediction you have to follow.`:'As you record more periods, Ritmi will gently show your rhythm here.'}</p><button onclick="Ritmi.go('insights')">See your history <b>→</b></button></div></section>`}
function trackView(m){const l=D.logs?.[selected]||{}, isP=periodSet().has(selected);m.innerHTML=`<section class="r-page">${label('Track · '+pretty(selected))}<div class="r-tracktop"><button class="r-back" onclick="Ritmi.go('today')">←</button><div><h1>How are you?</h1><p class="r-sub">Record only what feels useful. You can always come back.</p></div></div><div class="r-periodmark"><span>Period</span><button class="r-periodtoggle ${isP?'on':''}" onclick="Ritmi.togglePeriod()"><i></i><b>${isP?'Recorded':'Not recorded'}</b></button></div><div class="r-loglist">${Object.keys(fields).map(k=>`<button class="r-logrow ${l[k]?'has':''}" onclick="Ritmi.field('${k}')"><span>${cap(k)}</span><small>${l[k]||'Not recorded'}</small><b>›</b></button>`).join('')}<button class="r-logrow ${l.symptoms?.length?'has':''}" onclick="Ritmi.symptoms()"><span>Symptoms</span><small>${l.symptoms?.length?l.symptoms.join(', '):'Not recorded'}</small><b>›</b></button><button class="r-logrow ${D.notes?.[selected]?'has':''}" onclick="Ritmi.note()"><span>Note</span><small>${D.notes?.[selected]?'Written':'Optional'}</small><b>›</b></button></div><div class="r-section"><button class="r-secondary" onclick="Ritmi.pickDate()">Choose another date</button><button class="r-textdanger" onclick="Ritmi.clearDay()">Clear this day</button></div></section>`}
function cap(s){return s[0].toUpperCase()+s.slice(1)}
function calendarView(m){const d=new Date(monthCursor),y=d.getFullYear(),mo=d.getMonth(),first=new Date(y,mo,1).getDay(),days=new Date(y,mo+1,0).getDate(),ps=periodSet();let cells='';for(let i=0;i<first;i++)cells+='<i></i>';for(let n=1;n<=days;n++){const k=iso(new Date(y,mo,n));cells+=`<button class="r-day ${k===selected?'sel':''} ${ps.has(k)?'period':''} ${logged(k)?'logged':''}" onclick="Ritmi.date('${k}')">${n}</button>`}const st=cycles();m.innerHTML=`<section class="r-page">${label('Calendar')}<div class="r-calhead"><button onclick="Ritmi.month(-1)">‹</button><button class="r-monthlabel" onclick="Ritmi.jumpToday()"><h1>${monthName(d)}</h1></button><button onclick="Ritmi.month(1)">›</button></div><div class="r-week">${['S','M','T','W','T','F','S'].map(x=>`<span>${x}</span>`).join('')}</div><div class="r-calendar">${cells}</div><div class="r-legend"><span><i class="period-dot"></i> Period</span><span><i class="log-dot"></i> Recorded</span></div><div class="r-section"><div class="r-sectiontitle">Selected day</div><button class="r-selected" onclick="Ritmi.go('track')"><span><strong>${pretty(selected)}</strong><small>${logged(selected)||ps.has(selected)?'Recorded':'Nothing recorded'}</small></span><b>→</b></button></div><div class="r-section"><div class="r-sectiontitle">Cycle history</div><div class="r-history">${st.p.length?st.p.slice().reverse().map((x,i)=>`<button onclick="Ritmi.date('${x}');Ritmi.go('track')"><span>${pretty(x)}</span><small>${i<st.p.length-1?st.lengths[st.p.length-2-i]+' days':'latest period'}</small></button>`).join(''):'<p class="r-muted">Record a few periods and your history will start to take shape.</p>'}</div></div></section>`}
function insightsView(m){const st=cycles(),days=Object.keys(D.logs||{}).length,notes=Object.keys(D.notes||{}).length;const symptomCounts={};Object.values(D.logs||{}).forEach(l=>(l.symptoms||[]).forEach(s=>symptomCounts[s]=(symptomCounts[s]||0)+1));const top=Object.entries(symptomCounts).sort((a,b)=>b[1]-a[1]).slice(0,5);m.innerHTML=`<section class="r-page">${label('Your history')}<h1>Patterns, not verdicts.</h1><p class="r-sub">A simple reading of what you have recorded. Ritmi does not diagnose or tell you what your body should do.</p><div class="r-insighthero"><strong>${st.avg||'—'}</strong><span>average cycle length</span><p>${st.lengths.length?`${st.lengths.length} completed cycle${st.lengths.length>1?'s':''} recorded.`:'More cycle dates will make this view useful.'}</p></div><div class="r-section"><div class="r-sectiontitle">What you have given Ritmi</div><div class="r-facts"><div><strong>${st.p.length}</strong><span>period starts</span></div><div><strong>${days}</strong><span>tracked days</span></div><div><strong>${notes}</strong><span>notes</span></div></div></div><div class="r-section"><div class="r-sectiontitle">Most observed symptoms</div>${top.length?top.map(([s,n])=>`<div class="r-bar"><span>${cap(s)}</span><b>${n}</b><i style="--w:${Math.min(100,n/Math.max(1,top[0][1])*100)}%"></i></div>`).join(''):'<p class="r-muted">No symptoms have been recorded yet.</p>'}<p class="r-footnote">These are counts from your own entries, not medical conclusions.</p></div></section>`}
function knowledgeView(m){m.innerHTML=`<section class="r-page">${label('Knowledge')}<h1>Understand your body.</h1><p class="r-sub">A small, calm library. Plain language, useful context, no diagnosis.</p><div class="r-articles">${knowledge.map((a,i)=>`<button class="r-article" onclick="Ritmi.article(${i})"><small>0${i+1}</small><span><strong>${esc(a[0])}</strong><em>${esc(a[1])}</em></span><b>→</b></button>`).join('')}</div><div class="r-note">Ritmi can point you to accessible original sources. Education stays separate from your personal tracking data.</div></section>`}
function moreView(m){m.innerHTML=`<section class="r-page">${label('Ritmi')}<h1>Your space.</h1><p class="r-sub">The things you rarely need, kept out of the way until you do.</p><div class="r-menu-list"><button class="r-row" onclick="Ritmi.profiles()"><span>Profiles</span><b>→</b></button><button class="r-row" onclick="Ritmi.reminders()"><span>Reminders</span><b>→</b></button><button class="r-row" onclick="Ritmi.settings()"><span>Settings & privacy</span><b>→</b></button><button class="r-row" onclick="Ritmi.backup()"><span>Export / backup</span><b>→</b></button><button class="r-row" onclick="Ritmi.restore()"><span>Import / restore</span><b>→</b></button><button class="r-row" onclick="location.href='./community.html'"><span>Community</span><b>→</b></button><button class="r-row" onclick="Ritmi.support()"><span>Support Ritmi</span><b>→</b></button><button class="r-row danger" onclick="Ritmi.erase()"><span>Delete local data</span><b>→</b></button></div><div class="r-privacy"><strong>Local by default.</strong><br>No account. No ads. No subscription wall. Your health data stays in this browser unless you choose to export or back it up elsewhere.</div></section>`}
function menu(){document.querySelector('#r-layer').innerHTML=`<div class="r-menu-backdrop" onclick="Ritmi.closeMenu()"></div><nav class="r-menu-sheet"><button class="r-menu-close" onclick="Ritmi.closeMenu()">Close</button><div class="r-eyebrow">Ritmi</div><h2>Go somewhere.</h2>${[['today','Today','Your quiet overview'],['track','Track','Record what you notice'],['calendar','Calendar','Your dates and history'],['insights','Patterns','Read your own history'],['knowledge','Knowledge','Learn without pressure'],['more','More','Privacy and preferences']].map(x=>`<button class="r-navitem ${route===x[0]?'active':''}" onclick="Ritmi.go('${x[0]}');Ritmi.closeMenu()"><span><strong>${x[1]}</strong><small>${x[2]}</small></span><b>→</b></button>`).join('')}</nav>`}
function closeMenu(){document.querySelector('#r-layer').innerHTML=''}
function sheet(title,body){document.querySelector('#r-layer').innerHTML=`<div class="r-sheet-backdrop" onclick="Ritmi.close()"></div><section class="r-sheet"><button class="r-close" onclick="Ritmi.close()">Close</button><div class="r-eyebrow">Ritmi</div><h2>${esc(title)}</h2>${body}</section>`}
function field(k){const old=D.logs?.[selected]?.[k];sheet(cap(k),`<p>Choose one. You can change it later.</p><div class="r-choice">${fields[k].map(v=>`<button class="${old===v?'on':''}" onclick="Ritmi.setField('${k}','${v}')"><span>${cap(v)}</span>${old===v?'✓':''}</button>`).join('')}</div><button class="r-sheet-action" onclick="Ritmi.setField('${k}','')">Clear</button>`)}
async function setField(k,v){D.logs=D.logs||{};D.logs[selected]=D.logs[selected]||{};if(v)D.logs[selected][k]=v;else delete D.logs[selected][k];await save();close();render()}
function symptoms(){const old=new Set(D.logs?.[selected]?.symptoms||[]);sheet('Symptoms',`<p>Choose anything you noticed. Nothing here is a diagnosis.</p><div class="r-symptoms">${symptomList.map(s=>`<button class="${old.has(s)?'on':''}" data-sym="${esc(s)}" onclick="this.classList.toggle('on')">${cap(s)}</button>`).join('')}</div><button class="r-sheet-action" onclick="Ritmi.saveSymptoms()">Save symptoms</button>`)}
async function saveSymptoms(){D.logs=D.logs||{};D.logs[selected]=D.logs[selected]||{};D.logs[selected].symptoms=[...document.querySelectorAll('[data-sym].on')].map(x=>x.dataset.sym);await save();close();render()}
async function note(){const v=prompt('Note for '+pretty(selected),D.notes?.[selected]||'');if(v===null)return;D.notes=D.notes||{};if(v.trim())D.notes[selected]=v.trim();else delete D.notes[selected];await save();render()}
async function togglePeriod(){await togglePeriodCore();render()}
async function togglePeriodCore(){D.periods=D.periods||[];const i=D.periods.findIndex(x=>String(x.date||x)===selected);if(i>=0)D.periods.splice(i,1);else D.periods.push({date:selected});await save()}
async function markPeriod(){selected=today;await togglePeriodCore();render()}
function date(k){selected=k;monthCursor=new Date(`${k}T12:00:00`);route='track';render()}
function pickDate(){const v=prompt('Date (YYYY-MM-DD)',selected);if(v&&/^\d{4}-\d{2}-\d{2}$/.test(v)){selected=v;monthCursor=new Date(`${v}T12:00:00`);route='track';render()}}
function jumpToday(){selected=today;monthCursor=new Date(`${today}T12:00:00`);route==='calendar'?render():go('today')}
function month(n){monthCursor.setMonth(monthCursor.getMonth()+n);render()}
function article(i){const a=knowledge[i];sheet(a[0],`<p>${esc(a[1])}</p><p>Ritmi provides general educational information. It is not a diagnostic tool and does not replace professional medical advice.</p><div class="r-source">Original sources are shown here when this article is connected to the Ritmi knowledge index.</div>`)}
function close(){closeMenu();overlay=null}
function profiles(){sheet('Profiles',`<p>Separate cycles can live in this browser. Nothing is uploaded.</p><div class="r-profile-list">${(D.profiles||[]).map(p=>`<button class="r-profile-item" onclick="Ritmi.profile('${esc(p.id)}')"><span>${esc(p.name)}</span><small>${p.id===D.activeProfile?'Current':'Switch'}</small></button>`).join('')}</div><button class="r-sheet-action" onclick="Ritmi.addProfile()">Add profile</button>`)}
async function profile(id){if(!(D.profiles||[]).some(p=>p.id===id))return;D.activeProfile=id;await save();close();render()}
async function addProfile(){const name=prompt('Profile name','New profile');if(!name?.trim())return;const id='p-'+Math.random().toString(36).slice(2,8);D.profiles=D.profiles||[];D.profiles.push({id,name:name.trim(),type:'custom'});D.activeProfile=id;await save();close();render()}
function reminders(){sheet('Reminders',`<p>Reminder preferences stay local. Browser notification support varies by device.</p><div class="r-choice"><button onclick="Ritmi.reminder('period')"><span>Period reminder</span><span>${D.reminders?.find(x=>x.type==='period')?'On':'Off'}</span></button><button onclick="Ritmi.reminder('tracking')"><span>Tracking reminder</span><span>${D.reminders?.find(x=>x.type==='tracking')?'On':'Off'}</span></button></div>`)}
async function reminder(type){D.reminders=D.reminders||[];const i=D.reminders.findIndex(x=>x.type===type);if(i>=0)D.reminders.splice(i,1);else D.reminders.push({type,enabled:true});await save();reminders()}
function settings(){sheet('Settings & privacy',`<p>Ritmi is local-first. These preferences stay on this device.</p><div class="r-setting"><span>Cycle length</span><button onclick="Ritmi.cycleLength()">${D.settings?.cycleLength||28} days</button></div><div class="r-setting"><span>Period length</span><button onclick="Ritmi.periodLength()">${D.settings?.periodLength||5} days</button></div><div class="r-setting"><span>Reduced motion</span><button onclick="Ritmi.reduceMotion()">${D.settings?.reduceMotion?'On':'Off'}</button></div><div class="r-setting"><span>Private display</span><button onclick="Ritmi.privateDisplay()">${D.settings?.privateDisplay?'On':'Off'}</button></div>`)}
async function cycleLength(){const v=prompt('Average cycle length in days',D.settings?.cycleLength||28);if(!v||isNaN(v))return;D.settings.cycleLength=Math.max(15,Math.min(90,Number(v)));await save();settings()}
async function periodLength(){const v=prompt('Typical period length in days',D.settings?.periodLength||5);if(!v||isNaN(v))return;D.settings.periodLength=Math.max(1,Math.min(15,Number(v)));await save();settings()}
async function reduceMotion(){D.settings.reduceMotion=!D.settings.reduceMotion;await save();document.documentElement.classList.toggle('reduce-motion',D.settings.reduceMotion);settings()}
async function privateDisplay(){D.settings.privateDisplay=!D.settings.privateDisplay;await save();settings()}
function backup(){const blob=new Blob([JSON.stringify(D,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ritmi-backup-${today}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function restore(){const input=document.createElement('input');input.type='file';input.accept='application/json';input.onchange=async()=>{const f=input.files?.[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!x||typeof x!=='object')throw Error();if(!confirm('Replace current local data with this backup?'))return;await S.save(x);D=await S.snapshot();render()}catch{alert('That backup could not be restored.')}};input.click()}
function support(){location.href='https://buymeacoffee.com/ritmi'}
function erase(){if(confirm('Delete all Ritmi data stored in this browser?'))S.clear().then(()=>location.reload())}
function go(v){route=v;render()}
function openTrack(){route='track';selected=today;render()}
window.Ritmi={go,openTrack,menu,closeMenu:closeMenu,field,setField,symptoms,saveSymptoms,note,togglePeriod,markPeriod,clearDay:async()=>{if(!confirm('Clear all tracking and notes for this day?'))return;delete D.logs?.[selected];delete D.notes?.[selected];await save();render()},date,pickDate,jumpToday,month,article,close,profiles,profile,addProfile,reminders,reminder,settings,cycleLength,periodLength,reduceMotion,privateDisplay,backup,restore,support,erase};
S.snapshot().then(x=>{D=x;shell()}).catch(e=>{console.error(e);root.innerHTML='<p style="padding:24px">Ritmi could not open.</p>'});
})();