(()=>{'use strict';
const S=window.RitmiStorage;
const root=document.body;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const iso=d=>{const x=new Date(d);return `${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`};
const today=iso(new Date());
let data=null,view='today',selected=today,drawer=null;
const nav=[['today','Today'],['track','Track'],['calendar','Calendar'],['knowledge','Knowledge'],['more','More']];
const knowledge=[['Cycle basics','How the menstrual cycle is organised, what varies, and what a tracker can and cannot tell you.'],['Periods','Bleeding, spotting, period length and when patterns are worth discussing with a clinician.'],['Symptoms','A plain-language index for common symptoms and ways to record them without turning tracking into diagnosis.'],['Body literacy','Terms, observations and questions that can help you understand your own patterns.'],['Privacy','Why local storage matters, what exports contain, and how to keep your backup under your control.']];
function shell(){root.innerHTML=`<div id="ritmi-app"><header class="r-header"><button class="r-word" data-nav="today">Ritmi</button><button class="r-small" data-nav="more">More</button></header><main id="r-main"></main><nav class="r-nav">${nav.map(([id,t])=>`<button data-nav="${id}"><span>${icon(id)}</span><small>${t}</small></button>`).join('')}</nav></div>`;root.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>go(b.dataset.nav));render()}
function icon(id){return ({today:'◌',track:'＋',calendar:'□',knowledge:'i',more:'⋯'})[id]||'·'}
function go(v){view=v;drawer=null;render();scrollTo(0,0)}
async function save(){await S.save(data)}
function currentLogs(){return data.logs?.[selected]||{}}
function render(){const m=document.querySelector('#r-main');if(!m)return;document.querySelectorAll('.r-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));({today:todayView,track:trackView,calendar:calendarView,knowledge:knowledgeView,more:moreView}[view]||todayView)(m);if(drawer)renderDrawer()}
function todayView(m){const p=lastPeriod();const day=p?Math.max(1,Math.floor((new Date(today)-new Date(p))/86400000)+1):null;const next=p?add(p,data.settings?.cycleLength||28):null;m.innerHTML=`<section class="r-page"><div class="r-eyebrow">Today · ${nice(today)}</div><h1>${day?`Day ${day}`:'Start with today.'}</h1><p class="r-sub">${day?`Your cycle, without the dashboard.`:'Record a period whenever it happens. Ritmi learns only from what you choose to record.'}</p><div class="r-primary"><div><small>Today</small><strong>${day?`Cycle day ${day}`:'Nothing recorded'}</strong></div><button onclick="window.RitmiRebuild.openTrack()">Log today</button></div>${next?`<div class="r-line"><span>Expected next period</span><strong>${nice(next)}</strong></div>`:''}<div class="r-section"><div class="r-sectiontitle">Recently recorded</div>${recent()}</div><div class="r-section"><div class="r-sectiontitle">Your data</div><button class="r-row" onclick="window.RitmiRebuild.go('calendar')"><span>Look through your history</span><b>→</b></button><button class="r-row" onclick="window.RitmiRebuild.go('track')"><span>Record another day</span><b>→</b></button></div></section>`}
function trackView(m){const l=currentLogs();m.innerHTML=`<section class="r-page"><div class="r-eyebrow">Track · ${nice(selected)}</div><h1>What happened?</h1><p class="r-sub">Choose only what matters today. You can add more later.</p><div class="r-options"><button class="r-option ${l.bleeding?'chosen':''}" onclick="window.RitmiRebuild.toggle('bleeding')"><span>Bleeding</span><small>${l.bleeding||'Not recorded'}</small></button><button class="r-option ${l.pain?'chosen':''}" onclick="window.RitmiRebuild.toggle('pain')"><span>Pain</span><small>${l.pain||'Not recorded'}</small></button><button class="r-option ${l.mood?'chosen':''}" onclick="window.RitmiRebuild.toggle('mood')"><span>Mood</span><small>${l.mood||'Not recorded'}</small></button><button class="r-option ${l.energy?'chosen':''}" onclick="window.RitmiRebuild.toggle('energy')"><span>Energy</span><small>${l.energy||'Not recorded'}</small></button><button class="r-option ${l.sleep?'chosen':''}" onclick="window.RitmiRebuild.toggle('sleep')"><span>Sleep</span><small>${l.sleep||'Not recorded'}</small></button><button class="r-option ${l.symptoms?.length?'chosen':''}" onclick="window.RitmiRebuild.toggle('symptoms')"><span>Symptoms</span><small>${l.symptoms?.length?l.symptoms.join(', '):'None recorded'}</small></button></div><div class="r-section"><button class="r-row" onclick="window.RitmiRebuild.note()"><span>${data.notes?.[selected]?'Edit note':'Add a note'}</span><b>＋</b></button></div><div class="r-section"><button class="r-secondary" onclick="window.RitmiRebuild.pickDate()">Choose another date</button></div></section>`}
function calendarView(m){const d=new Date(selected);const y=d.getFullYear(),mo=d.getMonth();const first=new Date(y,mo,1).getDay();const days=new Date(y,mo+1,0).getDate();let cells='';for(let i=0;i<first;i++)cells+='<i></i>';for(let n=1;n<=days;n++){const key=iso(new Date(y,mo,n));const has=data.logs?.[key]||data.periods?.some(x=>String(x.date||x)===key);cells+=`<button class="r-day ${key===selected?'sel':''} ${data.periods?.some(x=>String(x.date||x)===key)?'period':''}" onclick="window.RitmiRebuild.date('${key}')">${n}</button>`}m.innerHTML=`<section class="r-page"><div class="r-eyebrow">Calendar</div><div class="r-calhead"><button onclick="window.RitmiRebuild.month(-1)">‹</button><h1>${d.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h1><button onclick="window.RitmiRebuild.month(1)">›</button></div><div class="r-week">${['S','M','T','W','T','F','S'].map(x=>`<span>${x}</span>`).join('')}</div><div class="r-calendar">${cells}</div><div class="r-section"><div class="r-sectiontitle">Selected day</div><div class="r-line"><span>${nice(selected)}</span><strong>${Object.keys(currentLogs()).length?'Recorded':'Nothing recorded'}</strong></div></div></section>`}
function knowledgeView(m){m.innerHTML=`<section class="r-page"><div class="r-eyebrow">Knowledge</div><h1>Learn at your pace.</h1><p class="r-sub">Plain-language information, not diagnoses or prescriptions.</p><div class="r-articles">${knowledge.map((x,i)=>`<button class="r-article" onclick="window.RitmiRebuild.article(${i})"><small>0${i+1}</small><span><strong>${esc(x[0])}</strong><em>${esc(x[1])}</em></span><b>→</b></button>`).join('')}</div></section>`}
function moreView(m){m.innerHTML=`<section class="r-page"><div class="r-eyebrow">More</div><h1>Keep Ritmi yours.</h1><p class="r-sub">Everything that changes how the app behaves or how your data moves.</p><div class="r-menu"><button class="r-row" onclick="window.RitmiRebuild.backup()"><span>Export backup</span><b>→</b></button><button class="r-row" onclick="window.RitmiRebuild.restore()"><span>Import backup</span><b>→</b></button><button class="r-row" onclick="window.RitmiRebuild.settings()"><span>Settings</span><b>→</b></button><button class="r-row" onclick="location.href='./community.html'"><span>Community</span><b>→</b></button><button class="r-row" onclick="window.RitmiRebuild.support()"><span>Support Ritmi</span><b>→</b></button><button class="r-row danger" onclick="window.RitmiRebuild.erase()"><span>Delete local data</span><b>→</b></button></div><div class="r-privacy">No account. No ads. No subscription wall. Your tracker data is kept locally in this browser. Export it and keep the backup wherever you choose.</div></section>`}
function recent(){const keys=Object.keys(data.logs||{}).sort().reverse().slice(0,3);return keys.length?keys.map(k=>`<button class="r-row" onclick="window.RitmiRebuild.date('${k}');window.RitmiRebuild.go('track')"><span>${nice(k)}</span><b>→</b></button>`).join(''):'<div class="r-muted">Nothing recorded yet.</div>'}
function lastPeriod(){const a=(data.periods||[]).map(x=>String(x.date||x)).sort();return a[a.length-1]||null}
function add(s,n){const d=new Date(s);d.setDate(d.getDate()+n);return iso(d)}
function nice(s){return new Date(`${s}T12:00:00`).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}
function openTrack(){go('track')}
async function toggle(k){data.logs=data.logs||{};data.logs[selected]=data.logs[selected]||{};const vals={bleeding:['light','medium','heavy','spotting'],pain:['none','mild','moderate','strong'],mood:['low','okay','good','high'],energy:['low','medium','high'],sleep:['poor','okay','good']};if(k==='symptoms'){const a=['cramps','headache','bloating','breast tenderness','nausea'];const old=data.logs[selected].symptoms||[];data.logs[selected].symptoms=old.length?[]:[a[0]]}else{const a=vals[k],old=data.logs[selected][k],i=Math.max(0,a.indexOf(old));data.logs[selected][k]=old?a[(i+1)%a.length]:a[0]}await save();render()}
async function note(){const v=prompt('Note for '+nice(selected),data.notes?.[selected]||'');if(v===null)return;data.notes=data.notes||{};if(v.trim())data.notes[selected]=v.trim();else delete data.notes[selected];await save();render()}
function date(k){selected=k;render()}
function pickDate(){const v=prompt('Date (YYYY-MM-DD)',selected);if(v&&/^\d{4}-\d{2}-\d{2}$/.test(v)){selected=v;render()}}
function month(n){const d=new Date(selected);d.setMonth(d.getMonth()+n);selected=iso(new Date(d.getFullYear(),d.getMonth(),1));render()}
function article(i){const x=knowledge[i];drawer={title:x[0],body:x[1]+' This section is intentionally concise. Ritmi provides general information and is not a diagnostic tool.'};renderDrawer()}
function renderDrawer(){let el=document.querySelector('#r-drawer');if(!el){el=document.createElement('div');el.id='r-drawer';root.appendChild(el)}el.innerHTML=`<div class="r-sheet"><button class="r-close" onclick="window.RitmiRebuild.close()">Close</button><div class="r-eyebrow">Knowledge</div><h2>${esc(drawer.title)}</h2><p>${esc(drawer.body)}</p></div>`}
function close(){document.querySelector('#r-drawer')?.remove();drawer=null}
function settings(){const r=prompt('Cycle length in days',data.settings?.cycleLength||28);if(r){data.settings={...data.settings,cycleLength:Math.max(15,Math.min(90,Number(r)||28))};save();render()}}
function support(){location.href='./community.html#support'}
function backup(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ritmi-backup.json';a.click();URL.revokeObjectURL(a.href)}
function restore(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{const f=i.files?.[0];if(!f)return;try{const x=JSON.parse(await f.text());await S.save(x);data=await S.snapshot();render();alert('Backup restored locally.')}catch{alert('That backup could not be restored.')}};i.click()}
async function erase(){if(!confirm('Delete all Ritmi data from this browser? This cannot be undone.'))return;await S.clear();data=await S.snapshot();render()}
window.RitmiRebuild={go,openTrack,toggle,note,date,pickDate,month,article,close,backup,restore,settings,support,erase};
(async()=>{data=await S.snapshot();root.classList.add('ritmi-rebuild');shell()})().catch(e=>{console.error(e);root.innerHTML='<p style="padding:24px">Ritmi could not open its local data.</p>'});
})();
