(()=>{'use strict';
const css=`
:root{--ritmi-bg:#08090c;--ritmi-fg:#f5f4ef;--ritmi-muted:#8f929c;--ritmi-line:#24262d;--ritmi-surface:#101216;--ritmi-accent:#d8f36a}
html,body{background:var(--ritmi-bg)!important;color:var(--ritmi-fg)!important}body{overflow-x:hidden}.rt-shell{min-height:100svh!important;background:var(--ritmi-bg)!important}.rt-main{width:100%!important;max-width:720px!important;margin:0 auto!important;padding:0 22px calc(92px + env(safe-area-inset-bottom))!important}.rt-view{display:none!important;padding:0!important}.rt-view.active{display:block!important}.rt-head{padding:52px 0 34px!important}.rt-kicker{font-size:10px!important;letter-spacing:.14em!important;text-transform:uppercase!important;color:var(--ritmi-accent)!important;font-weight:750!important}.rt-h1{font-size:clamp(42px,12vw,68px)!important;line-height:.93!important;letter-spacing:-.065em!important;margin:13px 0 15px!important;font-weight:750!important}.rt-lead{font-size:15px!important;line-height:1.55!important;color:var(--ritmi-muted)!important;max-width:560px!important}.rt-card{background:transparent!important;border:0!important;box-shadow:none!important;border-radius:0!important}.rt-section{margin:0 0 38px!important}.rt-sectionhead{display:flex!important;align-items:baseline!important;justify-content:space-between!important;padding:0 0 13px!important;margin:0!important;border-bottom:1px solid var(--ritmi-line)!important}.rt-sectionhead strong{font-size:16px!important;letter-spacing:-.025em!important}.rt-list{border-top:0!important}.rt-list>*{border-color:var(--ritmi-line)!important}.rt-nav{position:fixed!important;z-index:100!important;left:0!important;right:0!important;bottom:0!important;margin:0!important;padding:7px 12px calc(7px + env(safe-area-inset-bottom))!important;background:rgba(12,13,17,.94)!important;backdrop-filter:blur(20px) saturate(130%)!important;-webkit-backdrop-filter:blur(20px) saturate(130%)!important;border-top:1px solid var(--ritmi-line)!important;border-radius:0!important;box-shadow:none!important}.rt-navin{max-width:720px!important;margin:auto!important;display:grid!important;gap:2px!important}.rt-nav button{min-height:52px!important;border:0!important;border-radius:12px!important;background:transparent!important;color:#777a83!important;padding:7px 3px!important}.rt-nav button.active{background:rgba(216,243,106,.09)!important;color:var(--ritmi-fg)!important}.rt-nav button i{font-style:normal!important;font-size:16px!important;display:block!important;line-height:19px!important;margin-bottom:2px!important}.rt-nav button span{font-size:9px!important;letter-spacing:.01em!important}.rt-top,.rt-toolbar,.rt-profile{box-shadow:none!important}.rt-main button,.rt-main .rt-btn{min-height:44px!important}.rt-empty{padding:26px 0!important;color:var(--ritmi-muted)!important}.rt-sectionhead+*{margin-top:0!important}
/* Replace the dashboard feeling with breathing room. */
.rt-view.active .rt-card,.rt-view.active .rt-panel{margin-left:0!important;margin-right:0!important}
@media(min-width:700px){.rt-main{padding-left:32px!important;padding-right:32px!important}.rt-head{padding-top:78px!important}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
`;
function inject(){if(document.getElementById('ritmi-ui-v2'))return;const s=document.createElement('style');s.id='ritmi-ui-v2';s.textContent=css;document.head.appendChild(s)}
function simplify(){inject();const main=document.querySelector('.rt-main');if(!main)return false;const nav=document.querySelector('.rt-nav');const navin=document.querySelector('.rt-navin');if(nav&&navin){nav.style.gridTemplateColumns='1fr';navin.style.gridTemplateColumns='repeat(5,minmax(0,1fr))';navin.querySelectorAll('button').forEach(b=>{if(b.dataset.nav==='community')b.onclick=()=>location.href='./community.html'})}document.querySelectorAll('.rt-view').forEach(v=>{v.removeAttribute('style')});return true}
let n=0;function boot(){if(simplify())return;if(n++<100)setTimeout(boot,100)}boot();
})();
