/* Ritmi product layer v2: progressive feature expansion built from the XML handoff. */
(()=>{
'use strict';
const KEY='ritmi-v1';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const base=read();
if(!base)return;
const d=base;
d.profiles=d.profiles||[{id:'self',name:'My cycle',type:'self'}];
d.activeProfile=d.activeProfile||'self';
d.customFields=d.customFields||[];
d.journal=d.journal||{};
d.reminders=d.reminders||[];
d.lock=d.lock||{enabled:false,hash:''};
d.settings=d.settings||{notifications:false};
const persist=()=>localStorage.setItem(KEY,JSON.stringify(d));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const iso=()=>new Date().toISOString().slice(0,10);
const dateText=x=>new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long'}).format(new Date(x+'T12:00:00'));
const modal=window.openModal||((html)=>{document.getElementById('sheetContent').innerHTML=html;document.getElementById('modal').classList.add('open')});
const close=window.closeModal||(()=>document.getElementById('modal').classList.remove('open'));
const toast=window.toast||(()=>{});
function addStyle(){const s=document.createElement('style');s.textContent=`
.xrow{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:13px 0;border-bottom:1px solid var(--line)}.xrow:last-child{border-bottom:0}.xicon{width:34px;height:34px;border-radius:11px;background:rgba(255,255,255,.05);display:grid;place-items:center;color:var(--muted);flex:0 0 auto}.xgroup{display:flex;gap:9px;align-items:center;min-width:0}.xstack{display:grid;gap:4px}.xmuted{font-size:10px;color:var(--muted);line-height:1.4}.xlink{font-size:11px;color:var(--accent);cursor:pointer}.dangerline{color:var(--bad)}.locked{filter:blur(10px);pointer-events:none;user-select:none}.pin{letter-spacing:.35em;text-align:center;font-size:22px}.datepick{display:flex;gap:7px;overflow:auto;scrollbar-width:none}.datepick button{flex:0 0 auto;min-width:62px;padding:9px 8px;border:1px solid var(--line);border-radius:14px;font-size:9px;color:var(--muted)}.datepick button.active{background:var(--accent);color:#080a0b;border-color:transparent;font-weight:750}.section-label{font-size:10px;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);font-weight:750;margin:17px 0 9px}.microchart{display:flex;align-items:end;height:80px;gap:5px}.microchart i{flex:1;min-height:5px;border-radius:8px 8px 2px 2px;background:linear-gradient(var(--accent),rgba(215,255,103,.12))}.feature-banner{padding:13px;border-radius:17px;background:linear-gradient(120deg,rgba(215,255,103,.09),rgba(156,227,255,.04));border:1px solid rgba(215,255,103,.16)}
`+(d.reduceMotion?'*{scroll-behavior:auto!important;animation:none!important;transition:none!important}':'');document.head.appendChild(s)}
addStyle();
function saveAndRefresh(){persist();if(window.renderAll)window.renderAll();if(window.renderSettings)window.renderSettings()}
function field(label,id,value,type='text',extra=''){return `<div class="field"><label>${label}</label><input id="${id}" type="${type}" value="${esc(value)}" ${extra}></div>`}
function openProfile(){modal(`<div class="eyebrow">Cycle profiles</div><h2>Whose rhythm?</h2><p>Keep separate records on this device. Nothing is uploaded.</p><div id="profileRows">${d.profiles.map(p=>`<button class="choice ${p.id===d.activeProfile?'active':''}" data-profile="${p.id}"><strong>${esc(p.name)}</strong><span>${p.type==='self'?'Your cycle':'Shared observation'}</span></button>`).join('')}</div><button class="ghost" id="addProfile" style="margin-top:10px">+ Add profile</button>`);document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{d.activeProfile=b.dataset.profile;persist();close();toast('Profile changed');});document.getElementById('addProfile').onclick=()=>{modal(`<div class="eyebrow">New profile</div><h2>Add a cycle</h2>${field('NAME','pname','Someone')}${field('TYPE','ptype','other')}<button class="primary" id="createProfile">Create profile</button>`);document.getElementById('createProfile').onclick=()=>{const name=document.getElementById('pname').value.trim()||'Someone';d.profiles.push({id:'p'+Date.now(),name,type:'other'});persist();close();toast('Profile added')};})}
function openJournal(date=iso()){
const note=d.journal[date]||'';
modal(`<div class="eyebrow">Journal</div><h2>${dateText(date)}</h2><p>A private space for context that structured tracking cannot capture.</p><textarea class="note" id="journalText" placeholder="How did today feel?">${esc(note)}</textarea><button class="primary" id="saveJournal">Save note</button><button class="ghost" id="deleteJournal" style="margin-top:8px">Delete note</button>`);
document.getElementById('saveJournal').onclick=()=>{const v=document.getElementById('journalText').value.trim();if(v)d.journal[date]=v;else delete d.journal[date];persist();close();toast(v?'Journal saved':'Journal cleared');};
document.getElementById('deleteJournal').onclick=()=>{delete d.journal[date];persist();close();toast('Journal deleted')};
}
function openDetailed(date=iso()){
const l=d.logs[date]||{};
const fields=[['pain','Pain'],['discharge','Discharge'],['medication','Medication'],['contraception','Contraception']];
modal(`<div class="eyebrow">Detailed log</div><h2>${dateText(date)}</h2><p>Keep the details that matter to you. Every field is optional.</p><div class="choice-grid">${fields.map(([k,n])=>`<button class="choice ${l[k]?'active':''}" data-detail="${k}"><strong>${n}</strong><span>${l[k]?'Logged':'Not logged'}</span></button>`).join('')}</div><div class="section-label">Private note</div><textarea class="note" id="detailNote" placeholder="Anything else…">${esc(l.note||'')}</textarea><button class="primary" id="saveDetailed">Save details</button>`);
document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{const k=b.dataset.detail;l[k]=!l[k];b.classList.toggle('active',l[k]);b.querySelector('span').textContent=l[k]?'Logged':'Not logged';});
document.getElementById('saveDetailed').onclick=()=>{l.note=document.getElementById('detailNote').value.trim();d.logs[date]=l;persist();close();toast('Details saved');if(window.renderAll)window.renderAll()};
}
function addCustom(){modal(`<div class="eyebrow">Personal signal</div><h2>What else matters?</h2><p>Create your own one tap tracker. Examples: headache, skin, focus, libido, medication taken.</p>${field('NAME','cfname','Headache')}<div class="choice-grid"><button class="choice active" data-kind="toggle"><strong>Toggle</strong><span>On / off</span></button><button class="choice" data-kind="scale"><strong>Scale</strong><span>1 to 5</span></button></div><button class="primary" id="createCustom">Add signal</button>`);let kind='toggle';document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;document.querySelectorAll('[data-kind]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.getElementById('createCustom').onclick=()=>{const name=document.getElementById('cfname').value.trim();if(!name)return toast('Add a name');d.customFields.push({id:'c'+Date.now(),name,kind});persist();close();toast('Signal added')}}
function openReminders(){modal(`<div class="eyebrow">Reminders</div><h2>Gentle, not noisy.</h2><p>Browser reminders are optional. Ritmi never needs a server to know your schedule.</p><div class="notice">Notifications depend on browser permission and device support. The schedule is stored locally.</div><div class="field"><label>REMINDER TIME</label><input id="remTime" type="time" value="${esc(d.reminders[0]?.time||'20:00')}"></div><div class="field"><label>MESSAGE</label><input id="remMsg" value="${esc(d.reminders[0]?.message||'A quiet moment to check in with Ritmi.')}" ></div><button class="primary" id="saveReminder">Save reminder</button><button class="ghost" id="clearReminder" style="margin-top:8px">Remove reminder</button>`);document.getElementById('saveReminder').onclick=async()=>{if('Notification' in window&&Notification.permission==='default')try{await Notification.requestPermission()}catch{}d.reminders=[{id:'daily',time:document.getElementById('remTime').value,message:document.getElementById('remMsg').value.trim(),enabled:true}];persist();close();toast('Reminder saved')};document.getElementById('clearReminder').onclick=()=>{d.reminders=[];persist();close();toast('Reminder removed')}}
async function hashPin(pin){const b=new TextEncoder().encode(pin+'|ritmi-local');const h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function setupLock(){modal(`<div class="eyebrow">App lock</div><h2>Protect the entrance.</h2><p>The lock hides Ritmi behind a local passcode. This is an interface lock, not a guarantee against a compromised device.</p>${field('PASSCODE','pin1','','password','inputmode="numeric" maxlength="8"')}${field('CONFIRM','pin2','','password','inputmode="numeric" maxlength="8"')}<button class="primary" id="enableLock">Enable lock</button>`);document.getElementById('enableLock').onclick=async()=>{const a=document.getElementById('pin1').value,b=document.getElementById('pin2').value;if(a.length<4||a!==b)return toast('Passcodes must match');d.lock={enabled:true,hash:await hashPin(a)};persist();close();toast('App lock enabled');showGate()}}
function showGate(){if(!d.lock?.enabled)return;const gate=document.createElement('div');gate.id='ritmiLockGate';gate.className='onboard';gate.innerHTML=`<div class="onboard-inner"><i class="mark"></i><h1>ritmi</h1><p>This space is locked on this device.</p><div class="onboard-card"><label>PASSCODE</label><input id="unlockPin" class="pin" type="password" inputmode="numeric" maxlength="8"></div><button class="primary" id="unlock">Unlock</button><div class="privacy-line">Local lock · no account required</div></div>`;document.body.appendChild(gate);document.getElementById('unlock').onclick=async()=>{const ok=(await hashPin(document.getElementById('unlockPin').value))===d.lock.hash;if(ok){gate.remove();toast('Unlocked')}else toast('Incorrect passcode')};}
function openPrivacyCenter(){modal(`<div class="eyebrow">Privacy</div><h2>Owned, locally.</h2><p>Ritmi's core record is stored in this browser. The product should remain useful without an account, advertising identifiers or cloud health processing.</p><div class="feature-banner"><strong>Local record</strong><div class="xmuted">${Object.keys(d.logs||{}).length} logged days · ${d.profiles.length} profile${d.profiles.length===1?'':'s'}</div></div><div class="section-label">Your controls</div><div class="xrow"><div><strong>Export</strong><div class="xmuted">Create a portable JSON backup.</div></div><button class="ghost" id="xExport">Export</button></div><div class="xrow"><div><strong>App lock</strong><div class="xmuted">Protect the interface with a local passcode.</div></div><button class="ghost" id="xLock">${d.lock.enabled?'Change':'Set up'}</button></div><button class="primary" onclick="closeModal()">Done</button>`);document.getElementById('xExport').onclick=()=>document.getElementById('exportBtn')?.click();document.getElementById('xLock').onclick=setupLock}
function injectMore(){const nav=document.getElementById('nav');if(!nav)return;const b=nav.querySelector('[data-view="history"]');if(b)b.innerHTML=`<span style="font-size:17px">•••</span><span>More</span>`;const more=document.getElementById('history');if(!more||more.dataset.ritmiEnhanced)return;more.dataset.ritmiEnhanced='1';const host=more.querySelector('.hero');if(host){const actions=document.createElement('div');actions.className='section';actions.innerHTML=`<div class="subnav" id="moreTabs"><button class="active" data-more="history">History</button><button data-more="journal">Journal</button><button data-more="profiles">Profiles</button><button data-more="reminders">Reminders</button><button data-more="settings">Settings</button></div><div id="morePanel"></div>`;host.after(actions);actions.querySelectorAll('[data-more]').forEach(x=>x.onclick=()=>renderMore(x.dataset.more));renderMore('history')}
}
function renderMore(tab){const p=document.getElementById('morePanel');if(!p)return;document.querySelectorAll('[data-more]').forEach(x=>x.classList.toggle('active',x.dataset.more===tab));if(tab==='history'){const logs=Object.entries(d.logs||{}).sort((a,b)=>b[0].localeCompare(a[0]));p.innerHTML=`<div class="card"><div class="section-label">Recent observations</div>${logs.slice(0,20).map(([day,l])=>`<div class="xrow"><div class="xgroup"><div class="xicon">${l.flow==='heavy'?'●':l.flow==='medium'?'◐':l.flow?'○':'·'}</div><div class="xstack"><strong>${dateText(day)}</strong><span class="xmuted">${Object.keys(l).filter(k=>k!=='note').join(' · ')||'No structured fields'}</span></div></div><button class="ghost" data-editday="${day}">Open</button></div>`).join('')||'<div class="empty">No observations yet.</div>'}</div>`;p.querySelectorAll('[data-editday]').forEach(x=>x.onclick=()=>openDetailed(x.dataset.editday));}
if(tab==='journal'){const entries=Object.entries(d.journal||{}).sort((a,b)=>b[0].localeCompare(a[0]));p.innerHTML=`<div class="card"><div class="section-head"><h2>Private journal</h2><button id="newJournal">New note</button></div>${entries.map(([day,n])=>`<div class="xrow"><div class="xstack"><strong>${dateText(day)}</strong><span class="xmuted truncate">${esc(n)}</span></div><button class="ghost" data-j="${day}">Edit</button></div>`).join('')||'<div class="empty">Your journal is empty.</div>'}</div>`;document.getElementById('newJournal').onclick=()=>openJournal();p.querySelectorAll('[data-j]').forEach(x=>x.onclick=()=>openJournal(x.dataset.j));}
if(tab==='profiles'){p.innerHTML=`<div class="card"><div class="section-head"><h2>Profiles</h2><button id="profileOpen">Manage</button></div>${d.profiles.map(x=>`<div class="xrow"><div><strong>${esc(x.name)}</strong><div class="xmuted">${x.id===d.activeProfile?'Active':'Available'} · ${x.type}</div></div>${x.id===d.activeProfile?'<span class="pill green">Active</span>':'<button class="ghost" data-setprofile="'+x.id+'">Use</button>'}</div>`).join('')}</div>`;document.getElementById('profileOpen').onclick=openProfile;p.querySelectorAll('[data-setprofile]').forEach(x=>x.onclick=()=>{d.activeProfile=x.dataset.setprofile;persist();renderMore('profiles');toast('Profile changed')})}
if(tab==='reminders'){p.innerHTML=`<div class="card"><div class="section-head"><h2>Reminders</h2><button id="remOpen">Configure</button></div>${d.reminders.length?d.reminders.map(r=>`<div class="xrow"><div><strong>${esc(r.time)}</strong><div class="xmuted">${esc(r.message)}</div></div><span class="pill green">Local</span></div>`).join(''):'<div class="empty">No reminders configured.</div>'}</div>`;document.getElementById('remOpen').onclick=openReminders}
if(tab==='settings'){p.innerHTML=`<div class="card settings"><div class="setting"><div><strong>Journal on device</strong><small>Freeform notes remain in local browser storage.</small></div><span class="pill green">Local</span></div><div class="setting"><div><strong>Custom signals</strong><small>${d.customFields.length} personal signals configured.</small></div><button class="ghost" id="customOpen">Manage</button></div><div class="setting"><div><strong>App lock</strong><small>Require a local passcode at launch.</small></div><button class="ghost" id="lockOpen">${d.lock.enabled?'Enabled':'Set up'}</button></div></div>`;document.getElementById('customOpen').onclick=()=>modal(`<div class="eyebrow">Custom signals</div><h2>Your own vocabulary.</h2><p>Track what standard categories miss.</p>${d.customFields.map(x=>`<div class="xrow"><strong>${esc(x.name)}</strong><button class="ghost dangerline" data-delcustom="${x.id}">Delete</button></div>`).join('')}<button class="primary" id="addCustom">Add signal</button>`);document.getElementById('lockOpen').onclick=setupLock;}
}
function enhanceTrack(){const t=document.getElementById('track');if(!t||t.dataset.enhanced)return;t.dataset.enhanced='1';const panel=t.querySelector('.track-panel');if(!panel)return;const actions=document.createElement('div');actions.className='section';actions.innerHTML=`<div class="section-label">Deep log</div><div class="grid two"><button class="ghost" id="deepLog">Pain · discharge · medication</button><button class="ghost" id="journalLog">Write a journal note</button></div><div id="customSignals" class="section"></div>`;panel.append(actions);document.getElementById('deepLog').onclick=()=>openDetailed();document.getElementById('journalLog').onclick=()=>openJournal();renderCustomSignals()}
function renderCustomSignals(){const host=document.getElementById('customSignals');if(!host)return;const today=d.logs[iso()]||{};host.innerHTML=d.customFields.length?`<div class="section-label">Your signals</div><div class="log-grid">${d.customFields.map(x=>`<button class="log-btn ${today[x.id]?'active':''}" data-custom="${x.id}"><span class="log-icon">◌</span><span class="log-name">${esc(x.name)}</span><span class="log-sub">${today[x.id]?'Logged':'Tap to log'}</span></button>`).join('')}</div><button class="ghost" id="addCustomInline" style="margin-top:9px">+ Add personal signal</button>`:'';host.querySelectorAll('[data-custom]').forEach(b=>b.onclick=()=>{const id=b.dataset.custom;const z=d.logs[iso()]||{};z[id]=x=!z[id];d.logs[iso()]=z;persist();renderCustomSignals();toast(z[id]?'Logged':'Removed')});host.querySelector('#addCustomInline')?.addEventListener('click',addCustom)}
function installHeader(){const top=document.querySelector('.top');if(!top||top.dataset.enhanced)return;top.dataset.enhanced='1';const actions=top.querySelector('.top-actions')||top;const profile=document.createElement('button');profile.className='iconbtn';profile.setAttribute('aria-label','Profiles');profile.innerHTML='<span style="font-size:15px">◉</span>';profile.onclick=openProfile;actions.appendChild(profile);const old=document.getElementById('privacyBtn');if(old)old.onclick=openPrivacyCenter}
function patchMoreSettings(){const settings=document.getElementById('settings');if(!settings||settings.dataset.enhanced)return;settings.dataset.enhanced='1';const host=settings.querySelector('.about')||settings.querySelector('.section.card:last-child')||settings;const box=document.createElement('div');box.className='section card';box.innerHTML=`<div class="eyebrow">Ritmi controls</div><h3>Private by default</h3><div class="xrow"><div><strong>Profiles</strong><div class="xmuted">Separate personal records on this device.</div></div><button class="ghost" id="setProfiles">Manage</button></div><div class="xrow"><div><strong>Reminders</strong><div class="xmuted">Optional local browser reminders.</div></div><button class="ghost" id="setReminders">Configure</button></div><div class="xrow"><div><strong>App lock</strong><div class="xmuted">Protect the interface with a passcode.</div></div><button class="ghost" id="setLock">${d.lock.enabled?'Enabled':'Set up'}</button></div>`;settings.appendChild(box);document.getElementById('setProfiles').onclick=openProfile;document.getElementById('setReminders').onclick=openReminders;document.getElementById('setLock').onclick=setupLock}
function init(){injectMore();enhanceTrack();installHeader();patchMoreSettings();setTimeout(showGate,150);}
init();
window.RitmiFeatures={openJournal,openDetailed,openProfile,openReminders,addCustom,setupLock,renderMore};
})();
