/* Ritmi addon: preserves the v2 UI while folding in the handoff's deeper local-first features. */
(()=>{
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const iso=()=>new Date().toISOString().slice(0,10);
const dateText=x=>new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long'}).format(new Date(x+'T12:00:00'));
function findStore(){const preferred=['ritmi-v2','ritmi-v1','ritmi'];for(const k of preferred){try{const v=JSON.parse(localStorage.getItem(k)||'null');if(v&&typeof v==='object')return [k,v]}catch{}}for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);try{const v=JSON.parse(localStorage.getItem(k)||'null');if(v&&typeof v==='object'&&(v.logs||v.cycles||v.settings||v.profile))return [k,v]}catch{}}return null}
const hit=findStore(); if(!hit)return;
const [KEY,d]=hit;
d.profiles=Array.isArray(d.profiles)&&d.profiles.length?d.profiles:[{id:'self',name:'My cycle',type:'self'}];
d.activeProfile=d.activeProfile||d.profiles[0].id;
d.journal=d.journal&&typeof d.journal==='object'?d.journal:{};
d.customFields=Array.isArray(d.customFields)?d.customFields:[];
d.reminders=Array.isArray(d.reminders)?d.reminders:[];
d.lock=d.lock&&typeof d.lock==='object'?d.lock:{enabled:false,hash:''};
const save=()=>localStorage.setItem(KEY,JSON.stringify(d));
const toast=m=>{if(typeof window.toast==='function')window.toast(m);else{let t=document.querySelector('.toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}}};
const modal=html=>{if(typeof window.openModal==='function')window.openModal(html);else{const m=document.getElementById('modal'),s=document.getElementById('sheetContent');if(m&&s){s.innerHTML=html;m.classList.add('open')}}};
const close=()=>{if(typeof window.closeModal==='function')window.closeModal();else document.getElementById('modal')?.classList.remove('open')};
const field=(l,id,v='',type='text',extra='')=>`<div class="field"><label>${l}</label><input id="${id}" type="${type}" value="${esc(v)}" ${extra}></div>`;
function style(){if(document.getElementById('ritmi-addon-style'))return;const s=document.createElement('style');s.id='ritmi-addon-style';s.textContent=`.ra-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:13px 0;border-bottom:1px solid var(--line)}.ra-row:last-child{border-bottom:0}.ra-stack{display:grid;gap:4px;min-width:0}.ra-muted{font-size:10px;color:var(--muted);line-height:1.4}.ra-tabs{display:flex;gap:7px;overflow:auto;margin:0 0 13px;scrollbar-width:none}.ra-tabs button{flex:0 0 auto;border:1px solid var(--line);border-radius:999px;padding:8px 11px;font-size:10px;color:var(--muted)}.ra-tabs button.active{color:#080a0b;background:var(--accent);border-color:transparent;font-weight:750}.ra-banner{padding:14px;border:1px solid rgba(215,255,103,.16);border-radius:17px;background:linear-gradient(120deg,rgba(215,255,103,.09),rgba(156,227,255,.04))}`;document.head.appendChild(s)}
async function hashPin(pin){const b=new TextEncoder().encode(pin+'|ritmi-local');const h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function profileModal(){modal(`<div class="eyebrow">Cycle profiles</div><h2>Whose rhythm?</h2><p>Separate records stay on this device.</p>${d.profiles.map(p=>`<button class="choice ${p.id===d.activeProfile?'active':''}" data-ra-profile="${p.id}"><strong>${esc(p.name)}</strong><span>${p.type==='self'?'Your cycle':'Shared observation'}</span></button>`).join('')}<button class="ghost" id="ra-add-profile" style="margin-top:9px">+ Add profile</button>`);document.querySelectorAll('[data-ra-profile]').forEach(b=>b.onclick=()=>{d.activeProfile=b.dataset.raProfile;save();close();toast('Profile changed')});document.getElementById('ra-add-profile').onclick=()=>{modal(`<div class="eyebrow">New profile</div><h2>Add a cycle</h2>${field('NAME','ra-pname','Someone')}<button class="primary" id="ra-create-profile">Create profile</button>`);document.getElementById('ra-create-profile').onclick=()=>{const name=document.getElementById('ra-pname').value.trim()||'Someone';d.profiles.push({id:'p'+Date.now(),name,type:'other'});save();close();toast('Profile added')}}}
function journal(date=iso()){const n=d.journal[date]||'';modal(`<div class="eyebrow">Journal</div><h2>${dateText(date)}</h2><p>Private context that structured tracking cannot capture.</p><textarea class="note" id="ra-journal" placeholder="How did today feel?">${esc(n)}</textarea><button class="primary" id="ra-save-j">Save note</button><button class="ghost" id="ra-del-j" style="margin-top:8px">Delete note</button>`);document.getElementById('ra-save-j').onclick=()=>{const v=document.getElementById('ra-journal').value.trim();if(v)d.journal[date]=v;else delete d.journal[date];save();close();toast(v?'Journal saved':'Journal cleared')};document.getElementById('ra-del-j').onclick=()=>{delete d.journal[date];save();close();toast('Journal deleted')}}
function detailed(date=iso()){d.logs=d.logs||{};const l=d.logs[date]||{};const fields=[['pain','Pain'],['discharge','Discharge'],['medication','Medication'],['contraception','Contraception']];modal(`<div class="eyebrow">Detailed log</div><h2>${dateText(date)}</h2><p>Every field is optional.</p><div class="choice-grid">${fields.map(([k,n])=>`<button class="choice ${l[k]?'active':''}" data-ra-detail="${k}"><strong>${n}</strong><span>${l[k]?'Logged':'Not logged'}</span></button>`).join('')}</div><div class="section-label">Private note</div><textarea class="note" id="ra-detail-note" placeholder="Anything else…">${esc(l.note||'')}</textarea><button class="primary" id="ra-save-detail">Save details</button>`);document.querySelectorAll('[data-ra-detail]').forEach(b=>b.onclick=()=>{const k=b.dataset.raDetail;l[k]=!l[k];b.classList.toggle('active',l[k]);b.querySelector('span').textContent=l[k]?'Logged':'Not logged'});document.getElementById('ra-save-detail').onclick=()=>{l.note=document.getElementById('ra-detail-note').value.trim();d.logs[date]=l;save();close();toast('Details saved');window.renderAll?.()}}
function customManager(){modal(`<div class="eyebrow">Personal signals</div><h2>Your own vocabulary.</h2><p>Track what standard categories miss.</p>${d.customFields.map(x=>`<div class="ra-row"><div class="ra-stack"><strong>${esc(x.name)}</strong><span class="ra-muted">${esc(x.kind)}</span></div><button class="ghost" data-ra-del="${x.id}">Delete</button></div>`).join('')||'<div class="empty">No personal signals yet.</div>'}<button class="primary" id="ra-new-custom">Add signal</button></div>`);document.querySelectorAll('[data-ra-del]').forEach(b=>b.onclick=()=>{d.customFields=d.customFields.filter(x=>x.id!==b.dataset.raDel);save();customManager();toast('Signal removed')});document.getElementById('ra-new-custom').onclick=()=>{modal(`<div class="eyebrow">Personal signal</div><h2>What else matters?</h2>${field('NAME','ra-cname','Headache')}<div class="choice-grid"><button class="choice active" data-ra-kind="toggle"><strong>Toggle</strong><span>On / off</span></button><button class="choice" data-ra-kind="scale"><strong>Scale</strong><span>1 to 5</span></button></div><button class="primary" id="ra-create-custom">Add signal</button>`);let kind='toggle';document.querySelectorAll('[data-ra-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.raKind;document.querySelectorAll('[data-ra-kind]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.getElementById('ra-create-custom').onclick=()=>{const name=document.getElementById('ra-cname').value.trim();if(!name)return toast('Add a name');d.customFields.push({id:'c'+Date.now(),name,kind});save();close();toast('Signal added');renderCustom()}})}
function renderCustom(){const host=document.getElementById('ra-custom-host');if(!host)return;d.logs=d.logs||{};const today=d.logs[iso()]||{};host.innerHTML=d.customFields.length?`<div class="section-label">Your signals</div><div class="log-grid">${d.customFields.map(x=>`<button class="log-btn ${today[x.id]?'active':''}" data-ra-custom="${x.id}"><span class="log-icon">◌</span><span class="log-name">${esc(x.name)}</span><span class="log-sub">${today[x.id]?'Logged':'Tap to log'}</span></button>`).join('')}</div><button class="ghost" id="ra-manage-custom" style="margin-top:9px">Manage signals</button>`:'';host.querySelectorAll('[data-ra-custom]').forEach(b=>b.onclick=()=>{const id=b.dataset.raCustom;const z=d.logs[iso()]||{};z[id]=!z[id];d.logs[iso()]=z;save();renderCustom();toast(z[id]?'Logged':'Removed')});host.querySelector('#ra-manage-custom')?.addEventListener('click',customManager)}
function reminders(){modal(`<div class="eyebrow">Reminders</div><h2>Gentle, not noisy.</h2><p>The schedule stays local. Browser support varies by device.</p><div class="notice">Ritmi never needs a server to know your reminder schedule.</div>${field('REMINDER TIME','ra-time',d.reminders[0]?.time||'20:00','time')}${field('MESSAGE','ra-msg',d.reminders[0]?.message||'A quiet moment to check in with Ritmi.')}<button class="primary" id="ra-save-rem">Save reminder</button><button class="ghost" id="ra-clear-rem" style="margin-top:8px">Remove reminder</button>`);document.getElementById('ra-save-rem').onclick=async()=>{if('Notification'in window&&Notification.permission==='default')try{await Notification.requestPermission()}catch{}d.reminders=[{id:'daily',time:document.getElementById('ra-time').value,message:document.getElementById('ra-msg').value.trim(),enabled:true}];save();close();toast('Reminder saved')};document.getElementById('ra-clear-rem').onclick=()=>{d.reminders=[];save();close();toast('Reminder removed')}}
function lockSetup(){modal(`<div class="eyebrow">App lock</div><h2>Protect the entrance.</h2><p>A local interface lock. It is not a replacement for device security.</p>${field('PASSCODE','ra-pin1','','password','inputmode="numeric" maxlength="8"')}${field('CONFIRM','ra-pin2','','password','inputmode="numeric" maxlength="8"')}<button class="primary" id="ra-lock">Enable lock</button>`);document.getElementById('ra-lock').onclick=async()=>{const a=document.getElementById('ra-pin1').value,b=document.getElementById('ra-pin2').value;if(a.length<4||a!==b)return toast('Passcodes must match');d.lock={enabled:true,hash:await hashPin(a)};save();close();toast('App lock enabled');showGate()}}
function showGate(){if(!d.lock?.enabled||document.getElementById('ritmi-addon-gate'))return;const g=document.createElement('div');g.id='ritmi-addon-gate';g.className='onboard';g.innerHTML=`<div class="onboard-inner"><i class="mark"></i><h1>ritmi</h1><p>This space is locked on this device.</p><div class="onboard-card"><label>PASSCODE</label><input id="ra-unlock" class="pin" type="password" inputmode="numeric" maxlength="8"></div><button class="primary" id="ra-unlock-btn">Unlock</button><div class="privacy-line">Local lock · no account required</div></div>`;document.body.appendChild(g);document.getElementById('ra-unlock-btn').onclick=async()=>{if((await hashPin(document.getElementById('ra-unlock').value))===d.lock.hash){g.remove();toast('Unlocked')}else toast('Incorrect passcode')}}
function privacy(){modal(`<div class="eyebrow">Privacy</div><h2>Owned, locally.</h2><p>Your record remains in this browser unless you choose to export it.</p><div class="ra-banner"><strong>Local record</strong><div class="ra-muted">${Object.keys(d.logs||{}).length} logged days · ${d.profiles.length} profile${d.profiles.length===1?'':'s'}</div></div><div class="section-label">Controls</div><div class="ra-row"><div><strong>Export</strong><div class="ra-muted">Create a portable JSON backup.</div></div><button class="ghost" id="ra-export">Export</button></div><div class="ra-row"><div><strong>App lock</strong><div class="ra-muted">Protect the interface locally.</div></div><button class="ghost" id="ra-lock-open">${d.lock.enabled?'Change':'Set up'}</button></div><button class="primary" id="ra-privacy-done">Done</button>`);document.getElementById('ra-export').onclick=()=>document.getElementById('exportBtn')?.click();document.getElementById('ra-lock-open').onclick=lockSetup;document.getElementById('ra-privacy-done').onclick=close}
function install(){style();const top=document.querySelector('.top');if(top&&!top.dataset.ra){top.dataset.ra='1';const a=top.querySelector('.top-actions')||top;const b=document.createElement('button');b.className='iconbtn';b.setAttribute('aria-label','Cycle profiles');b.innerHTML='◉';b.onclick=profileModal;a.appendChild(b)}
const track=document.getElementById('track');if(track&&!document.getElementById('ra-custom-host')){const host=document.createElement('div');host.id='ra-custom-host';host.className='section';const panel=track.querySelector('.track-panel')||track;panel.appendChild(host);const row=document.createElement('div');row.className='grid two section';row.innerHTML='<button class="ghost" id="ra-deep">Detailed log</button><button class="ghost" id="ra-journal">Journal</button>';panel.appendChild(row);document.getElementById('ra-deep').onclick=()=>detailed();document.getElementById('ra-journal').onclick=()=>journal();renderCustom()}
const settings=document.getElementById('settings');if(settings&&!document.getElementById('ra-controls')){const box=document.createElement('div');box.id='ra-controls';box.className='section card';box.innerHTML=`<div class="eyebrow">Ritmi controls</div><h3>Private by default</h3><div class="ra-row"><div><strong>Profiles</strong><div class="ra-muted">Separate records on this device.</div></div><button class="ghost" id="ra-profiles">Manage</button></div><div class="ra-row"><div><strong>Reminders</strong><div class="ra-muted">Optional local reminders.</div></div><button class="ghost" id="ra-reminders">Configure</button></div><div class="ra-row"><div><strong>App lock</strong><div class="ra-muted">Protect the interface with a passcode.</div></div><button class="ghost" id="ra-lock-settings">${d.lock.enabled?'Enabled':'Set up'}</button></div><div class="ra-row"><div><strong>Personal signals</strong><div class="ra-muted">${d.customFields.length} configured.</div></div><button class="ghost" id="ra-custom-settings">Manage</button></div>`;settings.appendChild(box);document.getElementById('ra-profiles').onclick=profileModal;document.getElementById('ra-reminders').onclick=reminders;document.getElementById('ra-lock-settings').onclick=lockSetup;document.getElementById('ra-custom-settings').onclick=customManager}
showGate();window.RitmiFeatures={profileModal,journal,detailed,customManager,reminders,lockSetup,privacy};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,100));else setTimeout(install,100);
})();
