(()=>{'use strict';
const S=window.RitmiStorage,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pad=n=>String(n).padStart(2,'0'),iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,today=()=>iso(new Date()),day=d=>new Date(d+'T12:00:00'),pretty=d=>day(d).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}),add=(d,n)=>{const x=day(d);x.setDate(x.getDate()+n);return iso(x)},diff=(a,b)=>Math.round((day(b)-day(a))/86400000);
let D,view='today',date=today(),month=day(today());
const periods=()=>[...(D.periods||[])].map(x=>String(x.date||x)).sort(), pset=()=>new Set(periods());
function cycles(){const p=periods(),a=[];for(let i=1;i<p.length;i++)a.push(diff(p[i-1],p[i]));return{p,a,avg:a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):null}}
function save(){return S.save(D).then(()=>S.snapshot()).then(x=>D=x)}
function render(){const m=document.querySelector('#rv-main');if(!m)return;({today,track,calendar,patterns,knowledge,more}[view]||today)(m);window.scrollTo(0,0)}
function shell(){document.body.innerHTML='<div id="ritmi-app"><header class="rv-head"><button class="rv-brand" onclick="R.go(\'today\')">ritmi</button><div class="rv-tools"><button class="rv-date" onclick="R.pickDate()">'+new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'})+'</button><button class="rv-index" onclick="R.menu()" aria-label="Menu"><span></span><span></span><span></span></button></div></header><main id="rv-main"></main><div id="rv-layer"></div></div>'}
const label=x=>'<div class="rv-kicker">'+x+'</div>';
function today(m){const p=periods().at(-1),st=cycles(),cd=p?Math.max(1,diff(p,today())+1):null,next=p?add(p,Number(D.settings?.cycleLength||28)):null,l=D.logs?.[today()]||{};m.innerHTML='<section class="rv-page">'+label('Today')+'<h1>'+(cd?'Day '+cd:'Begin with yourself.')+'</h1><p>'+(cd?'A quiet view of what you have recorded.':'Start with a period date. Nothing else is required.')+'</p><div class="rv-orbit"><div class="rv-ring r1"></div><div class="rv-ring r2"></div><div class="rv-core"><strong>'+(cd||'—')+'</strong><span>'+(cd?'cycle day':'not started')+'</span></div><small>'+(next?'Estimated next period · '+pretty(next):'Record a period to begin your history')+'</small></div><div class="rv-actions"><button onclick="R.trackToday()"><b>+</b><span>Record today</span></button><button onclick="R.period()"><b>'+(pset().has(today())?'✓':'○')+'</b><span>'+(pset().has(today())?'Period recorded':'Mark period')+'</span></button><button onclick="R.go(\'calendar\')"><b>◌</b><span>Calendar</span></button></div><div class="rv-block"><div class="rv-blockhead"><span>Today</span><button onclick="R.trackToday()">Edit</button></div>'+[['Flow',l.flow],['Mood',l.mood],['Pain',l.pain!==undefined?l.pain:null],['Symptoms',l.symptoms?.length?l.symptoms.length+' recorded':null],['Note',D.notes?.[today()]?'Written':null]].map(x=>'<div class="rv-line"><span>'+x[0]+'</span><b>'+(x[1]!=null&&x[1]!==''?esc(String(x[1])):'Not recorded')+'</b></div>').join('')+'</div><div class="rv-note"><span>Your rhythm</span><p>'+(st.avg?'Your recorded cycles average '+st.avg+' days. That describes your history, not a rule for your body.':'Record a few period starts and Ritmi will begin showing your own history.')+'</p><button onclick="R.go(\'patterns\')">Read your patterns →</button></div></section>'}
const fields={flow:['none','spotting','light','medium','heavy'],pain:['0','1','2','3','4'],mood:['low','okay','good','high'],energy:['1','2','3','4','5'],sleep:['poor','restless','okay','good'],cervicalMucus:['dry','creamy','egg-white','watery'],contraception:['none','pill','iud','condom','other']};
const symptomOptions=['cramps','headache','bloating','breast tenderness','nausea','back pain','fatigue','acne','constipation','diarrhea','dizziness','cravings','insomnia','pelvic pain','mood changes','hot flashes'];
function track(m){const l=D.logs?.[date]||{},is=pset().has(date),custom=D.customSignals||[];m.innerHTML='<section class="rv-page">'+label('Track · '+pretty(date))+'<div class="rv-titleline"><button onclick="R.go(\'today\')">←</button><div><h1>How are you?</h1><p>Record only what feels useful. You can change it later.</p></div></div><div class="rv-period"><span>Period</span><button class="'+(is?'on':'')+'" onclick="R.period()"><i></i>'+(is?'Recorded':'Not recorded')+'</button></div><div class="rv-log">'+Object.keys(fields).map(k=>'<button onclick="R.field(\''+k+'\')"><span>'+k.replace(/([A-Z])/g,' $1')+'</span><small>'+(l[k]||'Not recorded')+'</small><b>›</b></button>').join('')+'<button onclick="R.symptoms()"><span>Symptoms</span><small>'+(l.symptoms?.length?l.symptoms.join(', '):'Not recorded')+'</small><b>›</b></button>'+custom.map((x,i)=>'<button onclick="R.custom('+i+')"><span>'+esc(x.name)+'</span><small>Personal signal</small><b>›</b></button>').join('')+'<button onclick="R.customManager()"><span>Custom signals</span><small>Create your own</small><b>›</b></button><button onclick="R.note()"><span>Note</span><small>'+(D.notes?.[date]?'Written':'Optional')+'</small><b>›</b></button></div><button class="rv-outline" onclick="R.pickDate()">Choose another date</button><button class="rv-clear" onclick="R.clearDay()">Clear this day</button></section>'}
function field(k){const old=D.logs?.[date]?.[k];layer(label(k)+'<h2>Choose one.</h2><p>You can change this later.</p><div class="rv-choices">'+fields[k].map(v=>'<button class="'+(old===v?'on':'')+'" onclick="R.setField(\''+k+'\',\''+v+'\')">'+esc(v)+(old===v?' ✓':'')+'</button>').join('')+'</div><button class="rv-primary" onclick="R.setField(\''+k+'\',\'\')">Clear</button>')}
async function setField(k,v){D.logs=D.logs||{};D.logs[date]=D.logs[date]||{};v?D.logs[date][k]=v:delete D.logs[date][k];await save();close();render()}
function symptoms(){const old=new Set(D.logs?.[date]?.symptoms||[]);layer(label('Symptoms')+'<h2>What did you notice?</h2><p>Observation only. Nothing here is a diagnosis.</p><div class="rv-symptoms">'+symptomOptions.map(s=>'<button class="'+(old.has(s)?'on':'')+'" data-s="'+esc(s)+'">'+esc(s)+(old.has(s)?' ✓':'')+'</button>').join('')+'</div><button class="rv-primary" onclick="R.saveSymptoms()">Save symptoms</button>');document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>b.classList.toggle('on'))}
async function saveSymptoms(){D.logs=D.logs||{};D.logs[date]=D.logs[date]||{};const a=[...document.querySelectorAll('[data-s].on')].map(x=>x.dataset.s);a.length?D.logs[date].symptoms=a:delete D.logs[date].symptoms;await save();close();render()}
function note(){layer(label('Note · '+pretty(date))+'<h2>Leave a note.</h2><textarea id="rv-note" rows="7" maxlength="1000" placeholder="Anything you want to remember…">'+esc(D.notes?.[date]||'')+'</textarea><button class="rv-primary" onclick="R.saveNote()">Save note</button>')}
async function saveNote(){const v=document.querySelector('#rv-note').value.trim();D.notes=D.notes||{};v?D.notes[date]=v:delete D.notes[date];await save();close();render()}
function calendar(m){const y=month.getFullYear(),mo=month.getMonth(),first=new Date(y,mo,1),off=first.getDay(),days=new Date(y,mo+1,0).getDate(),ps=pset();let g='';for(let i=0;i<off;i++)g+='<i></i>';for(let n=1;n<=days;n++){const k=iso(new Date(y,mo,n));g+='<button class="rv-day '+(k===date?'sel ':'')+(ps.has(k)?'period ':'')+(D.logs?.[k]||D.notes?.[k]?'logged':'')+'" onclick="R.date(\''+k+'\')">'+n+'</button>'}m.innerHTML='<section class="rv-page">'+label('Calendar')+'<div class="rv-calhead"><button onclick="R.month(-1)">‹</button><h1>'+first.toLocaleDateString(undefined,{month:'long',year:'numeric'})+'</h1><button onclick="R.month(1)">›</button></div><div class="rv-week">'+['S','M','T','W','T','F','S'].map(x=>'<span>'+x+'</span>').join('')+'</div><div class="rv-grid">'+g+'</div><div class="rv-legend"><span>● period</span><span>• recorded</span></div><div class="rv-block"><div class="rv-blockhead"><span>Selected day</span><button onclick="R.trackSelected()">Open</button></div><div class="rv-selected"><strong>'+pretty(date)+'</strong><small>'+(ps.has(date)||D.logs?.[date]||D.notes?.[date]?'Something recorded':'Nothing recorded')+'</small></div></div></section>'}
function patterns(m){const st=cycles(),counts={};Object.values(D.logs||{}).forEach(l=>(l.symptoms||[]).forEach(s=>counts[s]=(counts[s]||0)+1));const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,6);m.innerHTML='<section class="rv-page">'+label('Your history')+'<h1>Patterns, not verdicts.</h1><p>Ritmi reflects what you recorded. It does not diagnose or tell you what your body should do.</p><div class="rv-stat"><strong>'+(st.avg||'—')+'</strong><span>average cycle length</span><small>'+st.a.length+' completed cycles recorded</small></div><div class="rv-metrics"><div><strong>'+st.p.length+'</strong><span>period starts</span></div><div><strong>'+Object.keys(D.logs||{}).length+'</strong><span>tracked days</span></div><div><strong>'+Object.keys(D.notes||{}).length+'</strong><span>notes</span></div></div><div class="rv-block"><div class="rv-blockhead"><span>Most observed symptoms</span></div>'+(top.length?top.map(x=>'<div class="rv-bar"><span>'+esc(x[0])+'</span><b>'+x[1]+'</b><i style="width:'+Math.min(100,x[1]/top[0][1]*100)+'%"></i></div>').join(''):'<p class="rv-muted">No symptoms recorded yet.</p>')+'</div><p class="rv-disclaimer">Patterns are descriptive only. They are not medical conclusions.</p></section>'}
const articles=[['Cycle basics','Menstrual cycles vary. Tracking describes your history rather than defining what is normal.','https://www.nhs.uk/conditions/periods/periods-and-the-menstrual-cycle/'],['Periods and bleeding','Learn about periods, bleeding and when to seek medical advice.','https://www.nhs.uk/conditions/periods/'],['Symptoms','Common symptoms can be tracked as observations, not diagnoses.','https://www.nhs.uk/conditions/period-pain/'],['Body literacy','Use your record to prepare questions for a qualified professional.','https://www.acog.org/womens-health'],['Privacy by design','Learn how browser storage works and what local-first means.','https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API']];
function knowledge(m){m.innerHTML='<section class="rv-page">'+label('Knowledge')+'<h1>Understand your body.</h1><p>A small, attributed library. Ritmi is not a medical authority.</p><div class="rv-articles">'+articles.map((a,i)=>'<button onclick="R.article('+i+')"><small>0'+(i+1)+'</small><span><strong>'+a[0]+'</strong><em>'+a[1]+'</em></span><b>→</b></button>').join('')+'</div></section>'}
function more(m){m.innerHTML='<section class="rv-page">'+label('Ritmi')+'<h1>Your space.</h1><p>Privacy, backup, preferences and the community live here.</p><div class="rv-menu-list">'+[['profiles','Profiles'],['reminders','Reminders'],['settings','Settings & privacy'],['backup','Export / backup'],['restore','Import / restore']].map(x=>'<button onclick="R.'+x[0]+'()"><span>'+x[1]+'</span><b>→</b></button>').join('')+'<button onclick="location.href=\'./community.html\'"><span>Community</span><b>→</b></button><button onclick="location.href=\'./community-pro.html\'"><span>Community Pro</span><b>→</b></button><button onclick="R.support()"><span>Support Ritmi</span><b>→</b></button><button class="danger" onclick="R.erase()"><span>Delete local data</span><b>→</b></button></div><div class="rv-privacy"><strong>Local by default.</strong><br>No account. No ads. No subscription wall. Health data stays in this browser unless you export or back it up yourself.</div></section>'}
function layer(html){document.querySelector('#rv-layer').innerHTML='<div class="rv-backdrop" onclick="R.close()"></div><section class="rv-sheet"><button class="rv-x" onclick="R.close()">Close</button>'+html+'</section>'}function close(){document.querySelector('#rv-layer').innerHTML=''}function menu(){layer(label('Ritmi')+'<h2>Go somewhere.</h2>'+[['today','Today','Quiet overview'],['track','Track','Record what you notice'],['calendar','Calendar','History by date'],['patterns','Patterns','Your recorded history'],['knowledge','Knowledge','Learn without pressure'],['more','More','Privacy and preferences']].map(x=>'<button class="rv-navitem '+(view===x[0]?'active':'')+'" onclick="R.go(\''+x[0]+'\');R.close()"><span><strong>'+x[1]+'</strong><small>'+x[2]+'</small></span><b>→</b></button>').join(''))}
function pickDate(){layer(label('Choose a date')+'<h2>Look back.</h2><input id="rv-date-input" type="date" value="'+date+'" max="'+today()+'"><button class="rv-primary" onclick="R.setDate()">Open date</button>')}function setDate(){date=document.querySelector('#rv-date-input').value||today();view='track';close();render()}
async function period(){D.periods=D.periods||[];const i=D.periods.findIndex(x=>String(x.date||x)===date);i>=0?D.periods.splice(i,1):D.periods.push({date});await save();render()}
function clearDay(){if(!confirm('Clear all records for this day?'))return;delete D.logs?.[date];delete D.notes?.[date];D.periods=(D.periods||[]).filter(x=>String(x.date||x)!==date);save().then(render)}
function profiles(){layer(label('Profiles')+'<h2>Separate spaces, still local.</h2><p>Useful when a device is shared. No account is created.</p><div class="rv-profile">'+(D.profiles||[]).map(p=>'<div><span>'+esc(p.name)+'</span><small>'+(p.id===D.activeProfile?'Active':'Local')+'</small><button onclick="R.useProfile(\''+p.id+'\')">Use</button></div>').join('')+'</div><input id="rv-profile-name" placeholder="New profile name"><button class="rv-primary" onclick="R.addProfile()">Add profile</button>')}async function addProfile(){const n=document.querySelector('#rv-profile-name')?.value.trim();if(!n)return;D.profiles.push({id:'p-'+Date.now(),name:n,type:'local'});await save();profiles()}async function useProfile(id){D.activeProfile=id;await save();D=await S.snapshot();close();render()}
function reminders(){const r=D.reminders?.[0]||{};layer(label('Reminders')+'<h2>Gentle, optional reminders.</h2><p>Stored locally. Browser notifications depend on device support.</p><input id="rv-rem-time" type="time" value="'+(r.time||'20:00')+'"><input id="rv-rem-msg" maxlength="120" value="'+esc(r.message||'A quiet moment to check in with Ritmi.')+'"><button class="rv-primary" onclick="R.saveReminder()">Save reminder</button><button class="rv-outline" onclick="R.removeReminder()">Remove reminder</button>')}async function saveReminder(){if('Notification'in window&&Notification.permission==='default')try{await Notification.requestPermission()}catch{}D.reminders=[{time:document.querySelector('#rv-rem-time').value,message:document.querySelector('#rv-rem-msg').value,enabled:true}];await save();close();render()}async function removeReminder(){D.reminders=[];await save();close();render()}
function settings(){layer(label('Settings & privacy')+'<h2>Keep Ritmi yours.</h2><div class="rv-setting"><span>Storage</span><b>IndexedDB · local</b></div><div class="rv-setting"><span>Account</span><b>None</b></div><div class="rv-setting"><span>Ads</span><b>None</b></div><div class="rv-setting"><span>Analytics</span><b>None by design</b></div><label class="rv-source">AVERAGE CYCLE LENGTH</label><input id="rv-cycle" type="number" min="18" max="60" value="'+(D.settings?.cycleLength||28)+'"><label class="rv-source">AVERAGE PERIOD LENGTH</label><input id="rv-period" type="number" min="1" max="14" value="'+(D.settings?.periodLength||5)+'"><button class="rv-primary" onclick="R.saveSettings()">Save settings</button><button class="rv-outline" onclick="R.backup()">Export JSON</button><button class="rv-outline" onclick="R.encryptedBackup()">Encrypted backup</button><button class="rv-outline" onclick="R.restore()">Restore backup</button><p class="rv-source">No health data is sent to Ritmi.</p>')}async function saveSettings(){D.settings=D.settings||{};D.settings.cycleLength=Math.max(18,Math.min(60,+document.querySelector('#rv-cycle').value||28));D.settings.periodLength=Math.max(1,Math.min(14,+document.querySelector('#rv-period').value||5));await save();close();render()}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function backup(){download('ritmi-backup.json',JSON.stringify(D,null,2))}
const b64=x=>btoa(String.fromCharCode(...new Uint8Array(x))),u64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function cryptoKey(p,salt,use){return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveKey']),{name:'AES-GCM',length:256},false,use)}
async function encryptedBackup(){const p=prompt('Choose a backup password. Ritmi cannot recover it.');if(!p)return;try{const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await cryptoKey(p,salt,['encrypt']),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(D)));download('ritmi-encrypted-backup.ritmi',JSON.stringify({format:'ritmi-encrypted-backup',version:1,iterations:210000,salt:b64(salt),iv:b64(iv),data:b64(ct)}))}catch{alert('Encryption failed')}}
function restore(){layer(label('Import')+'<h2>Restore a backup.</h2><input id="rv-file" type="file" accept=".json,.ritmi,application/json"><button class="rv-primary" onclick="R.importFile()">Choose backup</button>')}async function importFile(){const f=document.querySelector('#rv-file')?.files?.[0];if(!f)return;try{const x=JSON.parse(await f.text());let data=x;if(x.format==='ritmi-encrypted-backup'){const p=prompt('Backup password');if(!p)return;const key=await cryptoKey(p,u64(x.salt),['decrypt']),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:u64(x.iv)},key,u64(x.data));data=JSON.parse(new TextDecoder().decode(plain))}await S.save(data);D=await S.snapshot();close();render()}catch{alert('That backup could not be restored.')}}
function custom(i){const x=(D.customSignals||[])[i];if(!x)return;const active=(D.logs?.[date]?.custom||[]).includes(x.id);layer(label('Custom signal')+'<h2>'+esc(x.name)+'</h2><p>Personal tracking, stored locally.</p><button class="rv-primary" onclick="R.toggleCustom(\''+x.id+'\')">'+(active?'Recorded · remove':'Record today')+'</button><button class="rv-outline" onclick="R.deleteCustom(\''+x.id+'\')">Delete signal</button>')}
function customManager(){layer(label('Custom signals')+'<h2>Your vocabulary.</h2><p>Create signals that fit your own experience.</p><div class="rv-signal-list">'+(D.customSignals||[]).map((x,i)=>'<button onclick="R.custom('+i+')"><span>'+esc(x.name)+'</span><b>→</b></button>').join('')+'</div><input id="rv-signal-name" maxlength="50" placeholder="e.g. migraine, appetite, skin"><button class="rv-primary" onclick="R.addSignal()">Add signal</button>')}async function addSignal(){const n=document.querySelector('#rv-signal-name')?.value.trim();if(!n)return;D.customSignals=D.customSignals||[];D.customSignals.push({id:'s-'+Date.now(),name:n});await save();customManager()}async function toggleCustom(id){D.logs=D.logs||{};D.logs[date]=D.logs[date]||{};const a=new Set(D.logs[date].custom||[]);a.has(id)?a.delete(id):a.add(id);D.logs[date].custom=[...a];await save();close();render()}async function deleteCustom(id){D.customSignals=(D.customSignals||[]).filter(x=>x.id!==id);Object.values(D.logs||{}).forEach(l=>l.custom=(l.custom||[]).filter(x=>x!==id));await save();close();render()}
function article(i){const a=articles[i];layer(label('Knowledge · 0'+(i+1))+'<h2>'+a[0]+'</h2><p>'+a[1]+'</p><a class="rv-primary" href="'+a[2]+'" target="_blank" rel="noopener">Read original source ↗</a><p class="rv-source">Ritmi is not a medical authority.</p>')}
function support(){layer(label('Support Ritmi')+'<h2>Keep it free.</h2><p>Ritmi is a hobby project. Optional support helps keep the core product free.</p><button class="rv-primary" onclick="window.open('https://www.buymeacoffee.com/','_blank','noopener')">Buy Me a Coffee</button>')}
function erase(){if(!confirm('Delete all Ritmi data stored in this browser? This cannot be undone.'))return;S.clear().then(()=>location.reload())}
function onboarding(){layer(label('Welcome to Ritmi')+'<h2>A tracker that does not need your identity.</h2><p>No account. No ads. No subscription wall. Your health record stays in this browser.</p><div class="rv-privacy"><strong>Your data stays here.</strong><br>Export it whenever you want. Back it up wherever you choose.</div><button class="rv-primary" onclick="R.finishOnboarding()">Start Ritmi</button>')}async function finishOnboarding(){D.onboarded=true;await save();close();render()}
window.R={go(v){view=v;render()},menu,close,trackToday(){date=today();view='track';render()},trackSelected(){view='track';render()},pickDate,setDate,period,date(v){date=v;view='track';render()},month(n){month=new Date(month.getFullYear(),month.getMonth()+n,1);render()},field,symptoms,saveSymptoms,note,saveNote,article,profiles,addProfile,useProfile,reminders,saveReminder,removeReminder,settings,saveSettings,backup,encryptedBackup,restore,importFile,support,erase,custom,customManager,addSignal,toggleCustom,deleteCustom,setField,clearDay,finishOnboarding};
S.snapshot().then(x=>{D=x;shell();render();if(!D.onboarded)onboarding()}).catch(e=>{console.error(e);document.body.innerHTML='<main style="padding:40px;font:16px system-ui">Ritmi could not open its local database. Reload to try again.</main>'});
})();