/* Ritmi 2.1 consolidated feature layer
   Product rules: free, no account, no ads, no feature locks, local-first health data.
   Community content is deliberately kept separate from the private health record.
*/
(()=>{
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const dateText=x=>new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(x+'T12:00:00'));
function findStore(){const preferred=['ritmi-v2','ritmi-v1','ritmi'];for(const k of preferred){try{const v=JSON.parse(localStorage.getItem(k)||'null');if(v&&typeof v==='object')return[k,v]}catch{}}for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);try{const v=JSON.parse(localStorage.getItem(k)||'null');if(v&&typeof v==='object'&&(v.logs||v.cycles||v.settings||v.profile))return[k,v]}catch{}}return null}
const hit=findStore();if(!hit)return;
const[KEY,d]=hit;
d.profiles=Array.isArray(d.profiles)&&d.profiles.length?d.profiles:[{id:'self',name:'My cycle',type:'self'}];
d.activeProfile=d.activeProfile||d.profiles[0].id;
d.journal=d.journal&&typeof d.journal==='object'?d.journal:{};
d.customFields=Array.isArray(d.customFields)?d.customFields:[];
d.reminders=Array.isArray(d.reminders)?d.reminders:[];
d.lock=d.lock&&typeof d.lock==='object'?d.lock:{enabled:false,hash:''};
d.communityDrafts=Array.isArray(d.communityDrafts)?d.communityDrafts:[];
const save=()=>localStorage.setItem(KEY,JSON.stringify(d));
const toast=m=>{if(typeof window.toast==='function')window.toast(m);else{const t=document.querySelector('.toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}}};
const modal=html=>{if(typeof window.openModal==='function')window.openModal(html);else{const m=document.getElementById('modal'),s=document.getElementById('sheetContent');if(m&&s){s.innerHTML=html;m.classList.add('open')}}};
const close=()=>{if(typeof window.closeModal==='function')window.closeModal();else document.getElementById('modal')?.classList.remove('open')};
const field=(l,id,v='',type='text',extra='')=>`<div class="field"><label>${l}</label><input id="${id}" type="${type}" value="${esc(v)}" ${extra}></div>`;
const section=(ey,h,p='')=>`<div class="eyebrow">${ey}</div><h2>${h}</h2>${p?`<p>${p}</p>`:''}`;
function style(){if(document.getElementById('ritmi-addon-style'))return;const s=document.createElement('style');s.id='ritmi-addon-style';s.textContent=`
.ra-list{display:grid;gap:8px;margin-top:12px}.ra-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:13px 0;border-bottom:1px solid var(--line)}.ra-row:last-child{border-bottom:0}.ra-stack{display:grid;gap:4px;min-width:0}.ra-muted{font-size:10px;color:var(--muted);line-height:1.45}.ra-banner{padding:15px;border:1px solid var(--line);border-radius:17px;background:rgba(255,255,255,.025)}.ra-link{display:block;text-decoration:none;color:inherit}.ra-link strong{display:block;font-size:12px}.ra-link span{display:block;color:var(--muted);font-size:10px;line-height:1.45;margin-top:4px}.ra-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.ra-small{font-size:9px;color:var(--faint);line-height:1.45}.ra-search{width:100%;border:1px solid var(--line);background:#0b0d11;color:var(--text);border-radius:13px;padding:12px}.ra-pro{border:1px solid rgba(215,255,103,.2);background:rgba(215,255,103,.045);border-radius:17px;padding:14px}.ra-post{padding:13px;border:1px solid var(--line);border-radius:15px;background:rgba(255,255,255,.02)}.ra-post+.ra-post{margin-top:8px}.ra-post h4{margin:0;font-size:12px}.ra-post p{font-size:11px;color:var(--muted);line-height:1.5;margin:6px 0 0}.ra-navgrid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.ra-navitem{text-align:left;padding:14px;border:1px solid var(--line);border-radius:16px;background:rgba(255,255,255,.025)}.ra-navitem strong{display:block;font-size:12px}.ra-navitem span{display:block;color:var(--muted);font-size:10px;line-height:1.4;margin-top:4px}.ra-plain{font-size:11px;color:var(--muted);line-height:1.6}.ra-scale{width:100%}
/* Keep the new layer quieter than the original premium treatment. */
body{background:var(--bg)!important}.card,.hero-orb{box-shadow:none!important}.card{background:rgba(255,255,255,.018)!important}.hero-orb{background:rgba(255,255,255,.018)!important}.orb{box-shadow:0 0 0 1px rgba(255,255,255,.05)!important;animation:none!important}
`;
document.head.appendChild(s)}
async function hashPin(pin){const b=new TextEncoder().encode(pin+'|ritmi-local');const h=await crypto.subtle.digest('SHA-256',b);return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function profiles(){modal(`${section('Profiles','Whose rhythm?','Keep separate records on this device. Ritmi does not need an account.')}${d.profiles.map(p=>`<button class="choice ${p.id===d.activeProfile?'active':''}" data-ra-profile="${p.id}"><strong>${esc(p.name)}</strong><span>${p.type==='self'?'Your cycle':'Shared observation'}</span></button>`).join('')}<button class="ghost" id="ra-add-profile" style="margin-top:9px">+ Add profile</button>`);document.querySelectorAll('[data-ra-profile]').forEach(b=>b.onclick=()=>{d.activeProfile=b.dataset.raProfile;save();close();toast('Profile changed');window.renderAll?.()});document.getElementById('ra-add-profile').onclick=()=>{modal(`${section('New profile','Add a cycle','Useful for a partner, friend, or dependent. Keep consent and privacy in mind.')}${field('NAME','ra-pname','Someone')}<button class="primary" id="ra-create-profile">Create profile</button>`);document.getElementById('ra-create-profile').onclick=()=>{const name=document.getElementById('ra-pname').value.trim()||'Someone';d.profiles.push({id:'p'+Date.now(),name,type:'other'});save();close();toast('Profile added')}}}
function journal(date=today()){const n=d.journal[date]||'';modal(`${section('Journal',dateText(date),'Private context that structured tracking cannot capture.') }<textarea class="note" id="ra-journal" placeholder="How did today feel?">${esc(n)}</textarea><button class="primary" id="ra-save-j">Save note</button><button class="ghost" id="ra-del-j" style="margin-top:8px">Delete note</button>`);document.getElementById('ra-save-j').onclick=()=>{const v=document.getElementById('ra-journal').value.trim();if(v)d.journal[date]=v;else delete d.journal[date];save();close();toast(v?'Journal saved':'Journal cleared')};document.getElementById('ra-del-j').onclick=()=>{delete d.journal[date];save();close();toast('Journal deleted')}}
function detailed(date=today()){d.logs=d.logs||{};const l=d.logs[date]||{};const fields=[['pain','Pain'],['discharge','Discharge'],['medication','Medication'],['contraception','Contraception']];modal(`${section('Detailed log',dateText(date),'Every field is optional.') }<div class="choice-grid">${fields.map(([k,n])=>`<button class="choice ${l[k]?'active':''}" data-ra-detail="${k}"><strong>${n}</strong><span>${l[k]?'Logged':'Not logged'}</span></button>`).join('')}</div><div class="section-label">Private note</div><textarea class="note" id="ra-detail-note" placeholder="Anything else…">${esc(l.note||'')}</textarea><button class="primary" id="ra-save-detail">Save details</button>`);document.querySelectorAll('[data-ra-detail]').forEach(b=>b.onclick=()=>{const k=b.dataset.raDetail;l[k]=!l[k];b.classList.toggle('active',l[k]);b.querySelector('span').textContent=l[k]?'Logged':'Not logged'});document.getElementById('ra-save-detail').onclick=()=>{l.note=document.getElementById('ra-detail-note').value.trim();d.logs[date]=l;save();close();toast('Details saved');window.renderAll?.()}}
function customManager(){modal(`${section('Personal signals','Your own vocabulary.','Track what the standard categories miss.')}${d.customFields.map(x=>`<div class="ra-row"><div class="ra-stack"><strong>${esc(x.name)}</strong><span class="ra-muted">${x.kind==='scale'?'1 to 5 scale':'Toggle'}</span></div><button class="ghost" data-ra-del="${x.id}">Delete</button></div>`).join('')||'<div class="ra-muted">No personal signals yet.</div>'}<button class="primary" id="ra-new-custom">Add signal</button>`);document.querySelectorAll('[data-ra-del]').forEach(b=>b.onclick=()=>{d.customFields=d.customFields.filter(x=>x.id!==b.dataset.raDel);save();customManager();toast('Signal removed')});document.getElementById('ra-new-custom').onclick=()=>{modal(`${section('Personal signal','What else matters?','Create a simple value you can log on any day.')}${field('NAME','ra-cname','Headache')}<div class="choice-grid"><button class="choice active" data-ra-kind="toggle"><strong>Toggle</strong><span>On / off</span></button><button class="choice" data-ra-kind="scale"><strong>Scale</strong><span>1 to 5</span></button></div><button class="primary" id="ra-create-custom">Add signal</button>`);let kind='toggle';document.querySelectorAll('[data-ra-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.raKind;document.querySelectorAll('[data-ra-kind]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.getElementById('ra-create-custom').onclick=()=>{const name=document.getElementById('ra-cname').value.trim();if(!name)return toast('Add a name');d.customFields.push({id:'c'+Date.now(),name,kind});save();close();toast('Signal added');renderCustom()}})}
function renderCustom(){const host=document.getElementById('ra-custom-host');if(!host)return;d.logs=d.logs||{};const z=d.logs[today()]||{};host.innerHTML=d.customFields.length?`<div class="section-label">Your signals</div><div class="log-grid">${d.customFields.map(x=>{const val=z[x.id];return`<div class="log-btn ${val!==undefined&&val!==false?'active':''}" style="display:block"><button style="display:block;width:100%;text-align:left" data-ra-custom="${x.id}"><span class="log-icon">◌</span><span class="log-name">${esc(x.name)}</span><span class="log-sub">${val!==undefined&&val!==false?(x.kind==='scale'?`Level ${val}`:'Logged'):'Tap to log'}</span></button>${x.kind==='scale'?`<input class="ra-scale" type="range" min="1" max="5" value="${Number(val)||1}" data-ra-scale="${x.id}" aria-label="${esc(x.name)} level">`:''}</div>`}).join('')}</div><button class="ghost" id="ra-manage-custom" style="margin-top:9px">Manage signals</button>`:'';host.querySelectorAll('[data-ra-custom]').forEach(b=>b.onclick=()=>{const id=b.dataset.raCustom;const f=d.customFields.find(x=>x.id===id);const o=d.logs[today()]||{};if(f?.kind==='scale'){o[id]=Math.min(5,(Number(o[id])||0)+1);if(o[id]>5)o[id]=1}else o[id]=o[id]?false:true;d.logs[today()]=o;save();renderCustom();toast(o[id]===false?'Removed':'Logged')});host.querySelectorAll('[data-ra-scale]').forEach(i=>i.oninput=()=>{const o=d.logs[today()]||{};o[i.dataset.raScale]=Number(i.value);d.logs[today()]=o;save();renderCustom()});host.querySelector('#ra-manage-custom')?.addEventListener('click',customManager)}
function reminders(){const r=d.reminders[0]||{};modal(`${section('Reminders','Gentle, not noisy.','Ritmi stores the schedule locally. This version does not claim a background notification service.')}${field('REMINDER TIME','ra-time',r.time||'20:00','time')}${field('MESSAGE','ra-msg',r.message||'A quiet moment to check in with Ritmi.')}<div class="ra-banner" style="margin-top:13px"><strong>Local schedule</strong><div class="ra-muted">Saving a time does not guarantee a notification while the app is closed. Browser and device support varies.</div></div><button class="primary" id="ra-save-rem">Save reminder</button><button class="ghost" id="ra-clear-rem" style="margin-top:8px">Remove reminder</button>`);document.getElementById('ra-save-rem').onclick=()=>{d.reminders=[{id:'daily',time:document.getElementById('ra-time').value,message:document.getElementById('ra-msg').value.trim(),enabled:true}];save();close();toast('Reminder saved')};document.getElementById('ra-clear-rem').onclick=()=>{d.reminders=[];save();close();toast('Reminder removed')}}
function lockSetup(){modal(`${section('App lock','Protect the entrance.','A local interface lock. It is not encryption and is not a replacement for device security.')}${field('PASSCODE','ra-pin1','','password','inputmode="numeric" maxlength="8"')}${field('CONFIRM','ra-pin2','','password','inputmode="numeric" maxlength="8"')}<button class="primary" id="ra-lock">Enable lock</button>${d.lock.enabled?'<button class="ghost" id="ra-disable-lock" style="margin-top:8px">Disable lock</button>':''}`);document.getElementById('ra-lock').onclick=async()=>{const a=document.getElementById('ra-pin1').value,b=document.getElementById('ra-pin2').value;if(a.length<4||a!==b)return toast('Passcodes must match');d.lock={enabled:true,hash:await hashPin(a)};save();close();toast('App lock enabled');showGate()};document.getElementById('ra-disable-lock')?.addEventListener('click',()=>{d.lock={enabled:false,hash:''};save();close();toast('App lock disabled')})}
function showGate(){if(!d.lock?.enabled||document.getElementById('ritmi-addon-gate'))return;const g=document.createElement('div');g.id='ritmi-addon-gate';g.className='onboard';g.innerHTML=`<div class="onboard-inner"><i class="mark"></i><h1>ritmi</h1><p>This space is locked on this device.</p><div class="onboard-card"><label>PASSCODE</label><input id="ra-unlock" class="pin" type="password" inputmode="numeric" maxlength="8"></div><button class="primary" id="ra-unlock-btn">Unlock</button><div class="privacy-line">Local interface lock · no account required</div></div>`;document.body.appendChild(g);document.getElementById('ra-unlock-btn').onclick=async()=>{if((await hashPin(document.getElementById('ra-unlock').value))===d.lock.hash){g.remove();toast('Unlocked')}else toast('Incorrect passcode')}}
function backupData(){const copy=JSON.parse(JSON.stringify(d));return{ritmiBackup:2,exportedAt:new Date().toISOString(),data:copy}}
function downloadBackup(){const blob=new Blob([JSON.stringify(backupData(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ritmi-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Backup saved')}
async function shareBackup(){const blob=new Blob([JSON.stringify(backupData(),null,2)],{type:'application/json'});const file=new File([blob],`ritmi-backup-${today()}.json`,{type:'application/json'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({title:'Ritmi backup',text:'My Ritmi backup',files:[file]});return}catch{}}downloadBackup()}
function importBackup(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{const f=i.files?.[0];if(!f)return;try{const raw=JSON.parse(await f.text());const incoming=raw?.data||raw;if(!incoming||typeof incoming!=='object')throw Error();if(!confirm('Replace this device\'s current Ritmi record with this backup?'))return;Object.keys(d).forEach(k=>delete d[k]);Object.assign(d,incoming);localStorage.setItem(KEY,JSON.stringify(d));toast('Backup restored');setTimeout(()=>location.reload(),400)}catch{toast('Could not read that backup')}};i.click()}
function privacy(){modal(`${section('Privacy','Owned, locally.','Ritmi does not require an account. Your health record is kept in this browser unless you choose to export it.') }<div class="ra-banner"><strong>Local record</strong><div class="ra-muted">${Object.keys(d.logs||{}).length} logged days · ${d.profiles.length} profile${d.profiles.length===1?'':'s'}</div></div><div class="ra-list"><div class="ra-row"><div><strong>Save backup</strong><div class="ra-muted">Download a portable JSON copy.</div></div><button class="ghost" id="ra-export">Save</button></div><div class="ra-row"><div><strong>Share backup</strong><div class="ra-muted">Send the file to a place you choose.</div></div><button class="ghost" id="ra-share">Share</button></div><div class="ra-row"><div><strong>Restore backup</strong><div class="ra-muted">Replace this browser's record with your chosen file.</div></div><button class="ghost" id="ra-import">Restore</button></div></div><div class="ra-small" style="margin-top:12px">Ritmi does not provide its own health-data cloud. Put backups wherever you trust: device storage, a private drive, or another place you control.</div><button class="primary" id="ra-privacy-done">Done</button>`);document.getElementById('ra-export').onclick=downloadBackup;document.getElementById('ra-share').onclick=shareBackup;document.getElementById('ra-import').onclick=importBackup;document.getElementById('ra-privacy-done').onclick=close}
const KNOW=[
['Cycle basics','ACOG','General menstrual cycle and period information from the American College of Obstetricians and Gynecologists.','https://www.acog.org/womens-health/faqs/menstruation-and-the-menstrual-cycle'],
['Menstrual health','NHS','Accessible health information about periods, symptoms and when to seek help.','https://www.nhs.uk/conditions/periods/'],
['Period pain','Mayo Clinic','Background on menstrual cramps, common causes and treatment considerations.','https://www.mayoclinic.org/diseases-conditions/menstrual-cramps/symptoms-causes/syc-20374938'],
['Menstrual cycle','Cleveland Clinic','A readable overview of cycle phases and common variation.','https://my.clevelandclinic.org/health/articles/10132-menstrual-cycle'],
['Period tracking & privacy','Mozilla Foundation','Independent privacy research on period and ovulation tracking apps.','https://www.mozillafoundation.org/fy-NL/nothing-personal/period-ovulation-trackers/']
];
function knowledge(){modal(`${section('Knowledge','Understand, do not obey.','Ritmi is a tracker, not a medical authority. Learn from accessible sources and follow the original source when you want more detail.') }<input class="ra-search" id="ra-know-search" placeholder="Search knowledge…" autocomplete="off"><div class="ra-list" id="ra-know-list">${KNOW.map((x,i)=>`<a class="ra-banner ra-link" data-ra-know="${i}" href="${x[3]}" target="_blank" rel="noopener"><strong>${esc(x[0])}</strong><span>${esc(x[2])}</span><span>Source: ${esc(x[1])} · Open original</span></a>`).join('')}</div><button class="primary" id="ra-knowledge-done">Done</button>`);const input=document.getElementById('ra-know-search');input.oninput=()=>{const q=input.value.toLowerCase();document.querySelectorAll('[data-ra-know]').forEach(a=>{a.style.display=a.textContent.toLowerCase().includes(q)?'block':'none'})};document.getElementById('ra-knowledge-done').onclick=close}
function community(){const drafts=d.communityDrafts;modal(`${section('Community','Talk without a profile.','This space is designed around anonymous submissions. Never include your name, contact details, exact location, or identifying health information.') }<div class="ra-banner"><strong>Anonymous by design</strong><div class="ra-muted">Ritmi does not create community accounts or profiles. The private health record and community drafts are separate.</div></div><div class="ra-list"><div class="ra-row"><div><strong>Write a post</strong><div class="ra-muted">Prepare a question or experience to share.</div></div><button class="ghost" id="ra-community-new">Post</button></div><div class="ra-row"><div><strong>Share a post</strong><div class="ra-muted">Use your device's share sheet. You choose where it goes.</div></div><button class="ghost" id="ra-community-share">Share</button></div></div><div class="ra-small" style="margin-top:12px">The current GitHub Pages build has no Ritmi-owned community server, so it cannot honestly present a live public feed. This keeps the health record local rather than quietly introducing a data-collection backend.</div>${drafts.length?`<div class="section-label">Local drafts</div>${drafts.slice(-5).reverse().map((p,i)=>`<div class="ra-post"><h4>${esc(p.title)}</h4><p>${esc(p.body)}</p><div class="ra-actions"><button class="ghost" data-ra-share-post="${drafts.length-1-i}">Share</button><button class="ghost" data-ra-delete-post="${drafts.length-1-i}">Delete</button></div></div>`).join(''):'<div class="ra-muted" style="margin-top:14px">No local drafts.</div>'}<button class="primary" id="ra-community-done">Done</button>`);document.getElementById('ra-community-new').onclick=communityComposer;document.getElementById('ra-community-share').onclick=()=>{const p=drafts.at(-1);if(p)sharePost(p);else toast('Write a post first')};document.querySelectorAll('[data-ra-share-post]').forEach(b=>b.onclick=()=>sharePost(drafts[Number(b.dataset.raSharePost)]));document.querySelectorAll('[data-ra-delete-post]').forEach(b=>b.onclick=()=>{d.communityDrafts.splice(Number(b.dataset.raDeletePost),1);save();community()});document.getElementById('ra-community-done').onclick=close}
function communityComposer(){modal(`${section('Anonymous post','What do you want to share?','Write without identifying yourself. Your post is saved only as a local draft until you choose to share it.')}${field('TITLE','ra-post-title','Question about my cycle') }<div class="field"><label>POST</label><textarea class="note" id="ra-post-body" placeholder="Describe the problem or question without personal identifiers."></textarea></div><button class="primary" id="ra-save-post">Save draft</button><button class="ghost" id="ra-share-now" style="margin-top:8px">Share now</button>`);document.getElementById('ra-save-post').onclick=()=>{const title=document.getElementById('ra-post-title').value.trim();const body=document.getElementById('ra-post-body').value.trim();if(!title||!body)return toast('Add a title and post');d.communityDrafts.push({title,body,createdAt:new Date().toISOString()});save();close();toast('Anonymous draft saved')};document.getElementById('ra-share-now').onclick=()=>{const title=document.getElementById('ra-post-title').value.trim(),body=document.getElementById('ra-post-body').value.trim();if(!title||!body)return toast('Add a title and post');sharePost({title,body})}}
async function sharePost(p){const text=`${p.title}\n\n${p.body}\n\nShared from Ritmi. No account.`;try{if(navigator.share){await navigator.share({title:p.title,text});return}}catch{}await navigator.clipboard?.writeText(text);toast('Post copied to clipboard')}
function communityPro(){modal(`${section('Community Pro','Find professional help.','A future directory should contain voluntary professional listings only. Ritmi does not ask users to create profiles.') }<div class="ra-pro"><strong>For professionals</strong><p class="ra-plain">If you are a qualified health professional and want to be listed, the listing should be voluntary and contactable directly. Useful fields include name, qualification, speciality, location or remote availability, registration details where relevant, and an external website.</p><button class="ghost" id="ra-pro-contact">Prepare a listing</button></div><div class="ra-banner" style="margin-top:10px"><strong>For everyone</strong><div class="ra-muted">Ritmi does not verify a professional's advice through the app. Check credentials and use appropriate local healthcare services for urgent concerns.</div></div><div class="ra-small" style="margin-top:12px">No professional directory backend is enabled in this GitHub Pages build. It will not pretend that an empty local list is a public directory.</div><button class="primary" id="ra-pro-done">Done</button>`);document.getElementById('ra-pro-contact').onclick=()=>{const text='Ritmi Community Pro listing\n\nName:\nQualification:\nSpeciality:\nLocation / remote:\nRegistration details:\nWebsite / contact:\n';if(navigator.share)navigator.share({title:'Ritmi Community Pro listing',text}).catch(()=>{});else navigator.clipboard?.writeText(text).then(()=>toast('Listing template copied'))};document.getElementById('ra-pro-done').onclick=close}
function help(){modal(`${section('Help','Simple answers.','Ritmi is intentionally straightforward.')}<div class="ra-list"><div class="ra-banner"><strong>Where is my health data?</strong><div class="ra-muted">In this browser's local storage. Ritmi's GitHub Pages site delivers the app but does not need a Ritmi health-data account.</div></div><div class="ra-banner"><strong>How do I move it?</strong><div class="ra-muted">Use Privacy to save a JSON backup, then restore that file on another device or browser.</div></div><div class="ra-banner"><strong>Does Ritmi sell data?</strong><div class="ra-muted">Ritmi has no feature that sells your health record and no account requirement. Community sharing is an explicit action you choose.</div></div><div class="ra-banner"><strong>Are predictions medical advice?</strong><div class="ra-muted">No. Cycle predictions are estimates based on the information you provide. Bodies vary and irregular cycles can make estimates less reliable.</div></div><div class="ra-banner"><strong>When should I seek care?</strong><div class="ra-muted">Use a qualified clinician or appropriate local health service for symptoms that concern you, severe or unusual pain, very heavy bleeding, fainting, pregnancy concerns, or emergencies.</div></div></div><button class="primary" id="ra-help-done">Done</button>`);document.getElementById('ra-help-done').onclick=close}
function about(){modal(`${section('About Ritmi','Made as a hobby. Kept free on purpose.','Ritmi was made because basic cycle tracking should not require a subscription wall.') }<div class="ra-banner"><strong>No account. No ads. No subscription wall.</strong><div class="ra-muted" style="margin-top:5px">Your health record stays on your device unless you choose to export it. There is nothing to unlock.</div></div><p class="ra-plain" style="margin-top:13px">Ritmi was not built to own your health data. It was built because we wanted a useful cycle tracker without the subscription wall. So we made the things we actually needed, kept the useful basics open, and left the rest to you.</p><p class="ra-plain">Most apps ask what they can get from your data. Ritmi asks what you need from your data.</p><a class="primary" style="display:block;text-align:center;text-decoration:none;margin-top:13px" href="https://www.buymeacoffee.com/" target="_blank" rel="noopener">Support Ritmi on Buy Me a Coffee</a><button class="ghost" id="ra-about-done" style="margin-top:8px">Done</button>`);document.getElementById('ra-about-done').onclick=close}
function more(){modal(`${section('Ritmi','More control, less noise.','The core tracker stays simple. The rest is here when you need it.') }<div class="ra-navgrid"><button class="ra-navitem" id="ra-more-knowledge"><strong>Knowledge</strong><span>Read accessible, attributed sources.</span></button><button class="ra-navitem" id="ra-more-community"><strong>Community</strong><span>Anonymous questions and sharing.</span></button><button class="ra-navitem" id="ra-more-pro"><strong>Community Pro</strong><span>Professional help, without user profiles.</span></button><button class="ra-navitem" id="ra-more-help"><strong>Help</strong><span>Privacy, backups, predictions and safety.</span></button><button class="ra-navitem" id="ra-more-privacy"><strong>Privacy & backup</strong><span>Export, restore and local controls.</span></button><button class="ra-navitem" id="ra-more-about"><strong>About Ritmi</strong><span>Why it exists and how it is funded.</span></button></div><button class="ghost" id="ra-more-close" style="width:100%;margin-top:10px">Done</button>`);document.getElementById('ra-more-knowledge').onclick=knowledge;document.getElementById('ra-more-community').onclick=community;document.getElementById('ra-more-pro').onclick=communityPro;document.getElementById('ra-more-help').onclick=help;document.getElementById('ra-more-privacy').onclick=privacy;document.getElementById('ra-more-about').onclick=about;document.getElementById('ra-more-close').onclick=close}
function install(){style();
const top=document.querySelector('.top');if(top&&!top.dataset.ra){top.dataset.ra='1';const a=top.querySelector('.top-actions')||top;const b=document.createElement('button');b.className='iconbtn';b.setAttribute('aria-label','Ritmi menu');b.innerHTML='⋯';b.onclick=more;a.appendChild(b)}
const track=document.getElementById('track');if(track&&!document.getElementById('ra-custom-host')){const host=document.createElement('div');host.id='ra-custom-host';host.className='section';const panel=track.querySelector('.track-panel')||track;panel.appendChild(host);const row=document.createElement('div');row.className='grid two section';row.innerHTML='<button class="ghost" id="ra-deep">Detailed log</button><button class="ghost" id="ra-journal">Journal</button>';panel.appendChild(row);document.getElementById('ra-deep').onclick=()=>detailed();document.getElementById('ra-journal').onclick=()=>journal();renderCustom()}
const settings=document.getElementById('settings');if(settings&&!document.getElementById('ra-controls')){const box=document.createElement('div');box.id='ra-controls';box.className='section card';box.innerHTML=`<div class="eyebrow">Ritmi controls</div><h3>Private by default</h3><div class="ra-row"><div><strong>Profiles</strong><div class="ra-muted">Separate records on this device.</div></div><button class="ghost" id="ra-profiles">Manage</button></div><div class="ra-row"><div><strong>Reminders</strong><div class="ra-muted">Optional local schedule.</div></div><button class="ghost" id="ra-reminders">Configure</button></div><div class="ra-row"><div><strong>App lock</strong><div class="ra-muted">Local interface lock, not encryption.</div></div><button class="ghost" id="ra-lock-settings">${d.lock.enabled?'Enabled':'Set up'}</button></div><div class="ra-row"><div><strong>Personal signals</strong><div class="ra-muted">${d.customFields.length} configured.</div></div><button class="ghost" id="ra-custom-settings">Manage</button></div>`;settings.appendChild(box);document.getElementById('ra-profiles').onclick=profiles;document.getElementById('ra-reminders').onclick=reminders;document.getElementById('ra-lock-settings').onclick=lockSetup;document.getElementById('ra-custom-settings').onclick=customManager}
showGate();window.RitmiFeatures={profiles,journal,detailed,customManager,reminders,lockSetup,privacy,knowledge,community,communityPro,help,about,more,downloadBackup,shareBackup,importBackup};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,100));else setTimeout(install,100);
})();
