(function(){
'use strict';
const KEY='ritmi-v1', PROFILE_KEY='ritmi-profiles-v1', UI_KEY='ritmi-ui-v1';
const $=id=>document.getElementById(id);
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
let profileStore=read(PROFILE_KEY,{});
let ui=read(UI_KEY,{reducedMotion:false});
function active(){return d.profiles.find(p=>p.id===d.activeProfile)||d.profiles[0]}
function snapshot(){let p=active();if(!p)return;profileStore[p.id]={logs:d.logs||{},journal:d.journal||{},lastPeriod:d.lastPeriod,cycleLength:d.cycleLength,periodLength:d.periodLength,cycleStarts:d.cycleStarts||[]};localStorage.setItem(PROFILE_KEY,JSON.stringify(profileStore))}
function loadProfile(id){snapshot();let p=d.profiles.find(x=>x.id===id);if(!p)return;let s=profileStore[id];if(s){d.logs=s.logs||{};d.journal=s.journal||{};d.lastPeriod=s.lastPeriod||d.lastPeriod;d.cycleLength=s.cycleLength||28;d.periodLength=s.periodLength||5;d.cycleStarts=s.cycleStarts||[]}else{d.logs={};d.journal={};d.cycleStarts=[d.lastPeriod]};d.activeProfile=id;save();localStorage.setItem(PROFILE_KEY,JSON.stringify(profileStore));render();more('profiles');toast('Profile changed')}
function migrate(){d.cycleStarts=Array.isArray(d.cycleStarts)?d.cycleStarts:[d.lastPeriod];d.cycleStarts=[...new Set(d.cycleStarts.filter(Boolean))].sort();if(!profileStore[d.activeProfile])snapshot();d.profiles.forEach(p=>{if(!profileStore[p.id])profileStore[p.id]={logs:{},journal:{},lastPeriod:d.lastPeriod,cycleLength:d.cycleLength,periodLength:d.periodLength,cycleStarts:[d.lastPeriod]}});localStorage.setItem(PROFILE_KEY,JSON.stringify(profileStore))}
function css(){if(ui.reducedMotion||d.reduceMotion)document.documentElement.style.setProperty('--ritmi-motion','0s');else document.documentElement.style.setProperty('--ritmi-motion','.28s')}
function injectCSS(){let s=document.createElement('style');s.textContent=`:root{--ritmi-motion:.28s}.view.active{animation-duration:var(--ritmi-motion)!important}.enhance-row{padding:14px 0;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:14px;align-items:center}.enhance-row:last-child{border-bottom:0}.enhance-copy strong{display:block;font-size:12px}.enhance-copy span{display:block;color:var(--muted);font-size:10px;line-height:1.45;margin-top:3px}.switch{width:48px;height:28px;border:1px solid var(--line);border-radius:999px;padding:3px;background:#ffffff08}.switch i{display:block;width:20px;height:20px;border-radius:50%;background:#6a6f7b;transition:.2s}.switch.on{background:#d7ff6715;border-color:#d7ff6750}.switch.on i{transform:translateX(20px);background:var(--acid)}.knowledge-item{padding:16px 0;border-bottom:1px solid var(--line)}.knowledge-item:last-child{border-bottom:0}.knowledge-item h3{margin:0 0 6px;font-size:15px}.knowledge-item p{margin:0;color:var(--muted);font-size:11px;line-height:1.55}.mini-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.mini-actions button{padding:8px 10px;border:1px solid var(--line);border-radius:11px;font-size:10px}.empty{color:var(--muted);font-size:11px;padding:18px 0}.profile-current{border:1px solid #d7ff6740;background:#d7ff670a;border-radius:18px;padding:13px;margin-bottom:11px}`;document.head.appendChild(s)}
function addMoreTabs(){let tabs=$('moreTabs');if(!tabs||tabs.querySelector('[data-tab="knowledge"]'))return;['knowledge','help'].forEach(t=>{let b=document.createElement('button');b.dataset.tab=t;b.textContent=t[0].toUpperCase()+t.slice(1);tabs.appendChild(b);b.onclick=()=>enhancedMore(t)})}
function enhancedMore(tab){if(tab==='knowledge'){document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('on',x.dataset.tab===tab));$('morePanel').innerHTML=`<div class="card"><div class="eyebrow">Knowledge</div><h2 style="margin:6px 0 4px">Understand the record.</h2><p class="muted">Short, plain-language context. No fear, no diagnosis, no wellness theatre.</p><div class="knowledge-item"><h3>Cycle length is not a rule</h3><p>Cycles vary. Ritmi uses your recorded history when it has enough data and labels estimates clearly.</p></div><div class="knowledge-item"><h3>Patterns need repetition</h3><p>A single observation can be useful, but repeated observations make personal patterns more meaningful.</p></div><div class="knowledge-item"><h3>Privacy is a product behaviour</h3><p>Your core record is kept in local browser storage. Export is user initiated. There is no account requirement for the local experience.</p></div><div class="knowledge-item"><h3>When something feels wrong</h3><p>Ritmi is a tracker, not a diagnostic tool. Persistent, severe or worrying symptoms should be discussed with an appropriate healthcare professional.</p></div></div>`;return}if(tab==='help'){document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('on',x.dataset.tab===tab));$('morePanel').innerHTML=`<div class="card"><div class="eyebrow">Help</div><h2 style="margin:6px 0 4px">Keep it simple.</h2><p class="muted">Everything important can be backed up, restored or removed from this device.</p><div class="mini-actions"><button id="helpExport">Export backup</button><button id="helpImport">Restore backup</button><button id="helpLock">App lock</button></div><div class="knowledge-item"><h3>Backup</h3><p>Export creates a JSON file containing your local Ritmi record. Keep it somewhere you trust.</p></div><div class="knowledge-item"><h3>Restore</h3><p>Restore replaces the current local record with the selected valid Ritmi backup after confirmation.</p></div><div class="knowledge-item"><h3>Privacy note</h3><p>Browser storage is not the same as encrypted storage. The current interface lock should not be treated as data-at-rest encryption.</p></div></div>`;$('helpExport').onclick=exportData;$('helpImport').onclick=restoreData;$('helpLock').onclick=lockSetup;return}more(tab)}
function restoreData(){let input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{let f=input.files&&input.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let incoming=JSON.parse(r.result);if(!incoming||typeof incoming!=='object'||typeof incoming.logs!=='object')throw Error();if(!confirm('Restore this backup? Your current local record will be replaced.'))return;localStorage.setItem(KEY,JSON.stringify(incoming));localStorage.removeItem(PROFILE_KEY);location.reload()}catch{toast('That backup is not a valid Ritmi file')}};r.readAsText(f)};input.click()}
function addSettingsControls(){let panel=$('morePanel');if(!panel||document.getElementById('restoreLocal'))return;let card=panel.querySelector('.card');if(!card)return;let wrap=document.createElement('div');wrap.innerHTML=`<div class="enhance-row"><div class="enhance-copy"><strong>Reduced motion</strong><span>Use calmer transitions and less movement.</span></div><button class="switch ${ui.reducedMotion||d.reduceMotion?'on':''}" id="motionToggle" aria-label="Reduced motion"><i></i></button></div><div class="enhance-row"><div class="enhance-copy"><strong>Backup & restore</strong><span>Your record can be exported or restored locally.</span></div><div class="mini-actions" style="margin:0"><button id="restoreLocal">Restore</button><button id="exportLocal">Export</button></div></div><div class="enhance-row"><div class="enhance-copy"><strong>Cycle history</strong><span>Record a confirmed cycle start to improve personal history.</span></div><button class="ghost" id="cycleStart">Record</button></div>`;card.appendChild(wrap);$('motionToggle').onclick=()=>{ui.reducedMotion=!(ui.reducedMotion||d.reduceMotion);d.reduceMotion=ui.reducedMotion;localStorage.setItem(UI_KEY,JSON.stringify(ui));save();css();addSettingsControls()};$('restoreLocal').onclick=restoreData;$('exportLocal').onclick=exportData;$('cycleStart').onclick=recordCycleStart}
function recordCycleStart(){let date=today();open(`<div class="eyebrow">Cycle history</div><h2>Record a start.</h2><p>Use the day your period actually started. This becomes part of your personal history and does not change past logs.</p><div class="field"><label>START DATE</label><input id="cycleStartDate" type="date" value="${date}"></div><button class="primary" id="saveCycleStart">Record cycle start</button>`);$('saveCycleStart').onclick=()=>{let x=$('cycleStartDate').value;if(!x)return toast('Choose a date');d.cycleStarts=[...new Set([...(d.cycleStarts||[]),x])].sort();d.lastPeriod=x;save();snapshot();close();render();toast('Cycle start recorded')}}
function enhanceProfiles(){let p=$('morePanel');if(!p)return;p.querySelectorAll('[data-p]').forEach(b=>{b.onclick=()=>loadProfile(b.dataset.p)});if(!p.querySelector('.profile-current')){let a=active(),box=document.createElement('div');box.className='profile-current';box.innerHTML=`<div class="eyebrow">Active profile</div><strong>${a?.name||'My cycle'}</strong><div class="muted small" style="margin-top:3px">${a?.type||'self'} · ${Object.keys(d.logs||{}).length} observation days</div>`;p.prepend(box)}}
function observe(){let target=$('morePanel');if(!target)return;new MutationObserver(()=>{if(document.querySelector('[data-tab="settings"].on'))addSettingsControls();if(document.querySelector('[data-tab="profiles"].on'))enhanceProfiles()}).observe(target,{childList:true,subtree:true})}
function patchProfileCreation(){document.addEventListener('click',e=>{if(e.target?.id==='pc'){setTimeout(()=>{let newest=d.profiles[d.profiles.length-1];if(newest&&!profileStore[newest.id]){profileStore[newest.id]={logs:{},journal:{},lastPeriod:today(),cycleLength:28,periodLength:5,cycleStarts:[today()]};localStorage.setItem(PROFILE_KEY,JSON.stringify(profileStore)}},50)}})}
function boot(){migrate();injectCSS();css();addMoreTabs();observe();patchProfileCreation();$('profileBtn')?.addEventListener('click',()=>setTimeout(enhanceProfiles,20));document.addEventListener('click',e=>{let b=e.target.closest('[data-tab]');if(b&&b.dataset.tab==='profiles')setTimeout(enhanceProfiles,20)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
